### ISSUE TITLE
[Question] How to set refresh token header name?

### ISSUE THREAD

**Issue by wayneworkman** [vimalloc/flask-jwt-extended#103]
Hello,

I'm trying to use refresh tokens with headers instead of cookies. How would I set the header name that I want to use?

Thanks,
Wayne

**Comment by vimalloc** [comment]
It looks like currently you can only set the expected header name globally for both access and refresh tokens using the `JWT_HEADER_NAME` option, instead of a unique names for them. If I recall correctly, the reason it was setup that way was because you can't have an endpoint decorated with both `@jwt_required` and `@jwt_refresh_token_required`, as they would clobber each other in the request context with how the code is currently written.

It don't think it would be too hard to modify this extension to allow a endpoint to be decorated by both the access and refresh required functions, and allow the headers to be split up into different names. What is your use case for this?

Cheers.

**Comment by wayneworkman** [comment]
My use case: I'm using the access tokens for users, and refresh tokens for embedded Linux devices. I've set user tokens to be good for 24 hours, and refresh tokens to be good for 365 days. Our UI is passing the regular access token via headers to the API.  I'd like to be able to pass the refresh tokens for our hardware devices in the header too instead of using cookies. Because when using cookies, I have to code for CSRF protections which isn't exactly simple. So yes I am using this library in a non-intended way but it's working good so far. I'm not asking you to change anything that doesn't align with the 'opinionated' structure of this library. But if it does align, yeah it'd make my life a little easier to use headers with refresh tokens instead of cookies.

**Comment by vimalloc** [comment]
If the goal is just to use refresh tokens with headers, you can absolutely do that right now. You can send them in using the same headers that the access tokens use, and everything should just work. If you want to change the header names, I’ll look at how
