### ISSUE TITLE
Support for headless JWT tokens

### ISSUE THREAD

**Issue by JustinTervala** [vimalloc/flask-jwt-extended#104]
According to this article (https://dev.to/neilmadden/7-best-practices-for-json-web-tokens) and others, including the header on a JWT might be a security vulnerability at worst and redundant at best:
>A JWT consists of a protected payload together with a plaintext "header" section. This can contain various bits of information such as the algorithms used to sign or encrypt the payload or application-specific information to be used by intermediaries on the network, e.g. for message routing. In a lot of cases, this information is redundant and it is downright dangerous to trust its contents anyway. If you do not need to interoperate with third parties that expect standard JWTs, you can save some space and eliminate a whole class of vulnerabilities by simply stripping off the header section when producing a JWT and then recreate it from known data before parsing. I call these "headless JWTs" and recommend you use them wherever you can.
Stripping the header is easy: just remove everything up to the first "." character in the encoded JWT. To reconstruct the JWT, just base64url-encode a fixed header identifying the known algorithm and parameters and prepend it to the headless JWT.

I have been working with an implementation of this feature which uses the app context to store the header, but I'm not sure this would be the best implementation. If this a feature people would like, I can continue development on this feature.

**Comment by vimalloc** [comment]
This extension is not vulnerable to the style of attacks described by these vulnerabilities, as we specify what algorithm to use to decode the token based on the `JWT_ALGORITHM` option, not on what the algorithm is defined in the JWT. This means our tokens only take up a little more space, but the performance hit there should be completely negligible.

I don't think it would be be too bad to change our JWTs to headless JWTs, it could be done with some `join` and `split` calls, and using the `JWT_ALGORITHM` to re-create the headers when decoding.

However, that may cause problems if these JWTs are being used in conjunction with other JWT providers/consumers, or if the JWT spec changed in the future and the underlying library we are using to make JWTs (pyjwt) updated their stuff to match. I would feel better about this if it was an option that we could pass to the underlying `jwt.encode()` and `jwt.decode()` functions, instead of tacked on to this extension.

**Comment by JustinTervala** [comment]
That could work. I was originally looking at making a PR to PyJWT, but I liked the idea of just stripping and re-adding the header onto the JWT before being passed to `jwt.encode()` and `jwt.decode()`. I do understand that concern though. Maybe the JWT encode and decode could have a `headless=False` parameter tacked onto their `encode()` and `decode()` functions of the `PyJWS` classes and Flask-JWT-extended could use something like a `JWT_HEADLESSS` config or something similar which would determine whether or not to use `headless=True` or `headless=False`. I'll look into adding that to PyJWT and see if they'll accept it.

**Comment by vimalloc** [comment]
That sounds great to me 👍

If they aren't interested in a patch like that, let me know, and we can further discuss adding as an option to this extension by itself.

Cheers.
