### ISSUE TITLE
Integration with flask-restful & error handling

### ISSUE THREAD

**Issue by ecatkins** [vimalloc/flask-jwt-extended#141]
Similar to #86, errors like SignatureExpiry are returning 500 rather than 4xx errors. 

However I am using flask-restful which does not have an error_handler, so the solutions in the referenced issue do not apply.

Flask-restful is briefly mentioned on the releases page [here ](https://github.com/vimalloc/flask-jwt-extended/releases), but setting `application.config['PROPAGATE_EXCEPTIONS'] = True` didn't have any effect for me.

Any insight into how I can correctly deal with error handling using flask-restful?

**Comment by vimalloc** [comment]
Minus the propagate_exceptions thing, I'm not sure of anything else that could cause problems with flask-restful right off hand. Could you provide a minimum example that I could use to troubleshoot this further?

**Comment by vimalloc** [comment]
Thanks. Sorry, I've been a bit busy these past couple days, but I'll try to make time to look at this today. Cheers.

**Comment by cesarmarroquin** [comment]
I also encountered this issue. I could not replicate it at all in development, but was getting 500s instead of 401s in production and staging. 

I was able to reproduce it by setting the debug setting to false in development mode, and the 500s showed up.  

I was able to fix it by setting `application.config['PROPAGATE_EXCEPTIONS'] = True`

**Comment by vimalloc** [comment]
It sounds like everything is all cleared up here. If that's not the case, please feel free to comment and re-open this issue :+1:

**Comment by zakizem** [comment]
Hi vimalloc, I have an urgent issue here.

I'm using jwt extended with flask restful, and I have on the client side, http requests that consumes my API.

The problem is when I send a POST request (that has a json body) to a protected endpoint, sometimes I get the response i'm waiting for (a 401 Unauthorized or a 200), but a lot of times (90% of the time) the request fails and I get in the Chrome debugger of the request Header 'Provisional headers are shown'.

Please note that this only happens in CHROME and it works fine in Firefox.
And it also only happens when I send data with my request, if I send a post request without Json content, everything's also fine.

We would think at first that the problem isn't coming from the API but from the client, but when I take off the JWT REQUIRED decorator from my endpoint, the request doesn't fail 100% of the time.

Here's my code:

My API endpoint:

`class InsertionReponses(Resource):
    decorators = [jwt_required]
    def post(self):
        # print(request)
        # data=request.get_json(force=True)
        return 'something'`

My request from the JavaScript client (I'm using Vue JS Framework):

`      var xmlHttp = new XMLHttpRequest(); // new HttpRequest instance
      xmlHttp.open("POST", "http://127.0.0.1:5000/envoiReponses", true);
      xmlHttp.setRequestHeader("Content-Type", "application/json");
      xmlHttp.withCredentials = true;
      xmlHttp.send(JSON.stringify(someJsonData));`

**Comment by alexding123** [comment]
I am encountering the issue, and 

> I also encountered this issue. I could not replicate it at all in development, but was getting 500s instead of 401s in production and staging.
> 
> I was able to reproduce it by setting the debug setting to false in development mode, and the 500s showed up.
> 
> I was able to fix it by setting `application.config['PROPAGATE_EXCEPTIONS'] = True`

doesn't exactly do the trick for my setup. 

I'm using Flask-Restful's [custom errors](https://flask-restful.readthedocs.io/en/0.3.5/extending.html#define-custom-error-messages). It is true that setting `application.config['PROPAGATE_EXCEPTIONS'] = True` fixes the errors propagating from JWT, but this setting also causes any custom error message to show up as 500s, instead of 400s. So if `PROPAGATE_EXCEPTIONS`, JWT errors don't work. If `not PROPAGATE_EXCEPTIONS`, custom errors break. It's a bit of an unexpected dilemma. 

Is there any way to work around this without requiring `PROPAGATE_EXCEPTIONS` to be set?

**Comment by paurakhsharma** [comment]
@alexding123 I am experiencing the same issue.
Did you find any workaround?

**Comment by alexding123** [comment]
@paurakhsharma 

I think I found a workaround to integrate custom errors. 
Here's my current setup:
Set `PROPAGATE_EXCEPTIONS = False`
Then overwrite the error handler `flask_restful.Api` object as such:
```Python
from flask import Blueprint
from flask_restful import Api as _Api

# some custom errors
class RoomDoesNotExist(Exception):
    pass

CUSTOM_ERRORS = {
'RoomDoesNotExist': {
        'message': "A room by that name does not exist.",
        'status': 404,
    },
}

class Api(_Api):
    def error_router(self, original_handler, e):
        """ Override original error_router to only custom errors and parsing error (from webargs)"""
        error_type = type(e).__name__.split(".")[-1] # extract the error class name as a string
        # if error can be handled by flask_restful's Api object, do so
        # otherwise, let Flask handle the error
        # the 'UnprocessableEntity' is included only because I'm also using webargs
        # feel free to omit it
        if self._has_fr_route() and error_type in list(CUSTOM_ERRORS) + ['UnprocessableEntity']:
            try:
                return self.handle_error(e)
            except Exception:
                pass  # Fall through to original handler

        return original_handler(e)

api_bp = Blueprint('api', __name__)
api = Api(api_bp, errors=CUSTOM_ERRORS)
```

This way, flask_restful's errors are handled by flask_restful's Api object, and other errors fall through to Flask's error handler.

**Comment by tumluliu** [comment]
@alexding123 many many thanks for your solution! That's the only way I've found so far to bypass this annoying issue

**Comment by d-rocham** [comment]
@mxhr that's the perfect fix, and much more simple. Thanks a lot!

**Comment by jeevi710** [comment]
> It sounds like everything is all cleared up here. If that's not the case, please feel free to comment and re-open this issue 👍

**Comment by ayinmursalin** [comment]
> @paurakhsharma
> 
> I think I found a workaround to integrate custom errors. Here's my current setup: Set `PROPAGATE_EXCEPTIONS = False` Then overwrite the error handler `flask_restful.Api` object as such:
> 
> ```python
> from flask import Blueprint
> from flask_restful import Api as _Api
> 
> # some custom errors
> class RoomDoesNotExist(Exception):
>     pass
> 
> CUSTOM_ERRORS = {
> 'RoomDoesNotExist': {
>         'message': "A room by that name does not exist.",
>         'status': 404,
>     },
> }
> 
> class Api(_Api):
>     def error_router(self, original_handler, e):
>         """ Override original error_router to only custom errors and parsing error (from webargs)"""
>         error_type = type(e).__name__.split(".")[-1] # extract the error class name as a string
>         # if error can be handled by flask_restful's Api object, do so
>         # otherwise, let Flask handle the error
>         # the 'UnprocessableEntity' is included only because I'm also using webargs
>         # feel free to omit it
>         if self._has_fr_route() and error_type in list(CUSTOM_ERRORS) + ['UnprocessableEntity']:
>             try:
>                 return self.handle_error(e)
>             except Exception:
>                 pass  # Fall through to original handler
> 
>         return original_handler(e)
> 
> api_bp = Blueprint('api', __name__)
> api = Api(api_bp, errors=CUSTOM_ERRORS)
> ```
> 
> This way, flask_restful's errors are handled by flask_restful's Api object, and other errors fall through to Flask's error handler.

This is the best solutions for Flask-Restful and Flask-JWT-Extended in Production
I also try the same, and don't need to add CUSTOM_ERRORS it still works

```python
class CustomApi(_Api):
    def error_router(self, original_handler, e):
        return original_handler(e)
```

and in resource you can simply add 

```python
auth_blueprint = Blueprint("auth", __name__, url_prefix="/api")
auth_api = CustomApi(auth_blueprint)
```

**Comment by ksoorya** [comment]
> Another solution for anyone who is hitting the 500 internal server error instead of the expected 401, 4XX error as expected when using flask_restful:
> 
> ```
> from flask import Flask
> from flask_restful import Resource, Api
> from flask_jwt import JWT, jwt_required
> 
> app = Flask(__name__)
> app.secret_key = "yourSecretKeyHere"
> api = Api(app, errors=Flask.errorhandler)
> ```
> 
> This enabled me to change from this before implementation:
> 
> ```
> {
>     "message": "Internal Server Error"
> }
> ```
> 
> To this post implementation:
> 
> ```
> {
>     "description": "Request does not contain an access token",
>     "error": "Authorization Required",
>     "status_code": 401
> }
> ```

The same issue occurred where a 500 error was returned instead of 401, but this issue only happened when running the application as a service. Your solution resolved it. Thank you!
