### ISSUE TITLE
disable flask-jwt across all routes

### ISSUE THREAD

**Issue by havok2063** [vimalloc/flask-jwt-extended#143]
I have a situation where I am building an API, which allows access to different datasets.  One dataset requires authentication and another dataset is public and does not.  I need to use the same defined API (and all its routes) for access.  Is there a way I can use flask-jwt for API authentication across all of my routes, but then disable it on a config setting or toggle? 

I currently apply the `jwt_required` decorator as a default to all my of routes from a single base class.  This works perfectly for the cases for private data.  I need a way to turn off the authentication system when a certain setting is applied.   Is there a way to disable the `jwt_required` decorator once applied, or to disable the flask-jwt extension all together?  Or maybe override it?

**Comment by vimalloc** [comment]
Two solutions I could think off right off hand. First would be to use `@jwt_optional` if both the public and private data sets are used in parallel, and then distinguish in the endpoint itself which dataset to return to the caller based on if an access token is present or not. Second solution would be to create a dummy `@jwt_required` decorator that you import if certain conditions are met, something like:


```python
# this is untested
import os
if not os.enviorn.get('PUBLIC'):
    from flask_jwt_extended import jwt_required
else:
    def jwt_required(fn):
        return fn
```

You can also take a look at #142, I think it would be related.

Hope this helps!

**Comment by havok2063** [comment]
Thanks!  Those are both decent suggestions.  I'll give those a try.

**Comment by vimalloc** [comment]
Another option is available for this issue with the new 3.9.1 release. You could build your own decorator instead of using the built in jwt_required decorator which checks if an environmental variable (or setting or whatever) is set, and if so don't do any token verification and store some dummy data in the context stack (ex:`ctx_stack.top.jwt = jwt_data` or `ctx_stack.top.jwt_user = sqlalchemy_user`). The context stack is important, as it is what various helper functions like like jwt_identity and get_jwt_claims working.

Messing with the context stack internals obviously isn't the most ideal solution, as if there are ever any changes to this library there is no guarantee that those will still work as expected. But this does provide a way to start using this functionality right now. Maybe I could expose a `set_jwt_token` and `set_jwt_user` or something to provide a stable API for modifying the context stack with ones own decorators 🤷‍♂️ 

Some docs on getting started with building your own decorators can been seen here: http://flask-jwt-extended.readthedocs.io/en/latest/custom_decorators.html

**Comment by nishant-ketu** [comment]
just use @jwt_optional

**Comment by pgalilea** [comment]
if not os.getenv('JWT_ON'): jwt_required = lambda fn: fn

**Comment by gpuente** [comment]
> Two solutions I could think off right off hand. First would be to use `@jwt_optional` if both the public and private data sets are used in parallel, and then distinguish in the endpoint itself which dataset to return to the caller based on if an access token is present or not. Second solution would be to create a dummy `@jwt_required` decorator that you import if certain conditions are met, something like:
> 
> ```python
> # this is untested
> import os
> if not os.enviorn.get('PUBLIC'):
>     from flask_jwt_extended import jwt_required
> else:
>     def jwt_required(fn):
>         return fn
> ```
> 
> You can also take a look at #142, I think it would be related.
> 
> Hope this helps!

I think that `jwt_required` should be:

```python
def jwt_required(*args, **kwargs):
    return lambda fn: fn
```

**Comment by Kolterdyx** [comment]
This is what I use for debugging:

```
def dummy_jwt_required(realm=None):
    def wrapper(fn):
        @wraps(fn)
        def decorator(*args, **kwargs):
            return fn(*args, **kwargs)
        return decorator
    return wrapper

auth_required = dummy_jwt_required if config['DEBUG'] else jwt_required

@app.route('/dashboard')
@auth_required()
def dashboard():
    ...
```
