### ISSUE TITLE
Is there conflicts when using flask-wtf csrf vs flask-jwt-extended csrf?

### ISSUE THREAD

**Issue by rlam3** [vimalloc/flask-jwt-extended#15]
Is there conflicts when using flask-wtf csrf vs flask-jwt-extended csrf? Especially when it comes to error handling both of these differently? Or are these both the same? Thanks!

http://flask-wtf.readthedocs.io/en/stable/config.html

**Comment by vimalloc** [comment]
I'm not familiar with how flask-wtf works internally, or if it would work with the csrf protection built into this. Looking at that config, as long as you set different headers names for the csrf protections (```WTF_CSRF_HEADERS``` and ```JWT_CSRF_HEADER_NAME```) then I wouldn't be surprised if  they worked together without conflict, but I couldn't say for sure.

That said, I'm not sure if using two different engines for this would be a good idea. It might be better just to pick one of the csrf protection schemes and use that throughout your app. Is there a specific reason you are looking at using both?

**Comment by rlam3** [comment]
Flask-wtf uses csrf_tokens for POST and PUT requests. So every time a request was either of those http types, then it would trigger a validation and see if a csrf_token was provided. That being said, is this how CSRF token works too for flask-jwt-extended? 

I ask because I'm using flask-wtf with csrf protection for my forms POST requests. And it may or may not interfere with the POST requests and JWT. 

As of right now. My POST requests which uses flask-jwt-extended all require me to retrieve a csrf_token from my server by using the `generate_csrf()` function from flask-wtf and then setting it into the http header `X-CSRFToken` prior to firing off the actual POST request.

http://flask-wtf.readthedocs.io/en/stable/api.html#module-flask_wtf.csrf

Otherwise, all my POST and PUT requests would be denied due to an expired/invalid/missing csrf_token

**Comment by vimalloc** [comment]
It looks like there is a few differences between how this extension and flask-wtf is handing CSRF protection. My application is using a double submit cookie, whereas I think flask-wtf is using an encrypted token pattern. Either should work fine, you can read more about them here if you are so inclined:

https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)_Prevention_Cheat_Sheet

Either of these libraries should work to prevent csrf attacks, I can't think of a reason why you should use both. I would recommend disabling csrf protection on one of the libraries and just using the csrf protection on the other library.

My application is doing csrf protection on all the endpoints (GET included), compared to just POST/PUT/PATCH that flask-wtf is doing. Mine is also probably a bit harder to use if you are using are using a traditional website (not a single page application) compared to flask-jwt. These might influence your choice of what library you want to handle the CSRF protection.

**Comment by stephane** [comment]
@vimalloc flask-jwt is loooking for a maintainer, do you think you could do that and merge both projects? https://twitter.com/mattupstate/status/790184050640162816

**Comment by vimalloc** [comment]
Hrmmm. If we wanted to merge the two projects, I would be happy to step up and maintain it. But merging them would cause breaking changes. There are some choices that I made in my project that were explicitly different than what he was doing, for example, just creating an access token and returning it however you want vs registering a pre-defined endpoint that looks for a username/password in json and return an access token.

Perhaps we could setup his way of doing stuff in my project and mark it as depreciated, and remove it over the next several version, or something along those lines. But if it came down to keeping them separate, I would prefer to maintain only this one, as it's what I'm actively using.

It would be ideal if I could talk to the people currently using flask-jwt and get their opinion on it. Perhaps I can make an issue that repo, and hope that people stop by to respond.

Thanks for letting me know about this. If you have any thought on the matter I would love to hear them.

**Comment by dusktreader** [comment]
@stephane @vimalloc @mattupstate One of the big appeals (to me) of flask-jwt is that it is really light-weight and targeted specifically at basic token based authentication. I do a lot of work with apis that don't (and won't) support cookies, so I prefer to stick with a semi-stateless mechanism of authenticating. So, I think flask-jwt-extended has some cool features, but I probably won't use it in my projects.

I agree that it might be nice to configure a few things, such as the authentication endpoint and defining how you expect the body of the post request to that endpoint. Also, I need to figure out if I can get the endpoint in vanilla flask-jwt to play nicely with swagger since I'm using flask-restplus.

I'm not exactly eager to volunteer to be a maintainer (I have a few too many hobbies, and one of them needs to be held and fed milk all the time =]). However, I would really like to see flask-jwt remain light-weight and targeted at apis specifically while still being maintained with issues and pull-requests addressed as they arrive.

**Comment by vimalloc** [comment]
For what it's worth, using cookies is this extension is totally optional, it defaults to not using them. By default, you don't have to use any of the extended features this provides. It would look like this:
http://flask-jwt-extended.readthedocs.io/en/latest/basic_usage.html

That said, I totally understand the desire to use something small and lightweight. That's why I'm hesitant to volunteer taking over as a maintainer for flask-jwt and merge this project into it, unless it's clear that is what the community actually wants. Perhaps if someone else were to maintain it we could work together to direct users to the extension that would make most sense for their needs.

Thanks for the feedback!

**Comment by rlam3** [comment]
@vimalloc I really think that these projects are completely separate from each other and should remain that way in the long run because like you said, it does provide a breaking changes. I like this library because of the fact that new features and security measures are added in. Keep up the good work!

@dusktreader
To be honest, I migrated from flask-jwt to flask-jwt-extended. It was an easy migration and set up.
The decorator from flask-jwt is the same as flask-jwt-extended. You probably won't notice any difference. Partly because this project was inspired by flask-jwt to begin with. :) 

Cheers!

**Comment by vimalloc** [comment]
I'm going to close this. Lets to any further discussion in the issue on flask-jwt's page, or in a new issue here.

Thanks guys. :)
