### ISSUE TITLE
CSRF in cookie read incorrect key name

### ISSUE THREAD

**Issue by joshuaavalon** [vimalloc/flask-jwt-extended#150]
Version: 3.8.1

In `view_decorators.py`

```python
def _decode_jwt_from_cookies(request_type):
    if request_type == 'access':
        cookie_key = config.access_cookie_name
        csrf_header_key = config.access_csrf_cookie_name
    else:
        cookie_key = config.refresh_cookie_name
        csrf_header_key = config.refresh_csrf_cookie_name

    encoded_token = request.cookies.get(cookie_key)
    if not encoded_token:
        raise NoAuthorizationError('Missing cookie "{}"'.format(cookie_key))

    if config.csrf_protect and request.method in config.csrf_request_methods:
        csrf_value = request.cookies.get(csrf_header_key, None)
        if not csrf_value:
            raise CSRFError("Missing CSRF token in cookies")
    else:
        csrf_value = None

    return decode_token(encoded_token, csrf_value=csrf_value)
```

`access_csrf_header_name` should be `access_csrf_cookie_name` and  `refresh_csrf_header_name` should be `refresh_csrf_cookie_name`.

Also, it reads from headers instead of cookies

**Comment by vimalloc** [comment]
It is correct the way it is now. If it was reading the csrf token from the cookies then it would not offer any csrf protection what so ever. The protection scheme employeed here is called double submit verification if you are intrested in the details of it. There is some information available about this in the tokens in cookies page if you are interested: http://flask-jwt-extended.readthedocs.io/en/latest/tokens_in_cookies.html

**Comment by joshuaavalon** [comment]
@vimalloc The current approach always fail if cookie is used and CSRF is enabled because CSRF is set to cookies. How should I resolve it then?
.

**Comment by vimalloc** [comment]
It fails that way because it is totally vulnerable to a cross site forgery request (https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)). The solution is to implement the strategy outline in the paragraphs bellow the first code block here (http://flask-jwt-extended.readthedocs.io/en/latest/tokens_in_cookies.html) to perform a double submit token verification verification (https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)_Prevention_Cheat_Sheet#Double_Submit_Cookie). This insures that no CSRF attack is happening. 

The tl;dr version is you need to grab the CSRF token via javascript in your frontend and pass that in as an additional header to any state changing request that you make to your backend (POST, PUT, PATCH, DELET by default).
