### ISSUE TITLE
User claims loader on Blueprint ?

### ISSUE THREAD

**Issue by johaven** [vimalloc/flask-jwt-extended#162]
I have to authenticate in separate way users and external applications, for this i use two different blueprints.
```python
@api_users.before_request
@jwt_required
@user_loader
def before_request():
    pass

@api_external_apps.before_request
@jwt_required
@external_apps_loader
def before_request():
    pass
```
But the user_claims_loader is global to all the app and i use different identities for users and apps.

How can i solve this ?

**Comment by vimalloc** [comment]
My first thought is you don't have to pass a string in as the `identity` argument of `create_access_token` (see: http://flask-jwt-extended.readthedocs.io/en/latest/tokens_from_complex_object.html). I'm thinking it should be simple enough to pass some object in as the identity that could distinguish between the users and external applications when creating a JWT, and then do an if statement on that to set the user_claims in the token according to your applications needs.

**Comment by johaven** [comment]
This is actually the right method, I'm ok with that, thank you for pointing this out.
But in terms of modularity, it requires to put all the logic in a single piece of code (in "user_claims_loader" and "user_identity_loader", which are in fact global to the application).
It also forces to import the objects in the same place to compare the object instance type and create appopriate rules. In my case all my code consists of modules that are independent and only import the function "required", which annoys me it is finally that I have to somehow export my logic and my objects while it could remain in modules which are on separate blueprint.

:)

**Comment by johaven** [comment]
Another idea would be to authorize generated token only on certain routes or blueprints.
These are only reflective tracks that could bring nice features for security.

**Comment by vimalloc** [comment]
I imagine something could be done using flask without needing any changes to this application. If you can register the blueprints before doing the `jwt.init_app` call, I think you could probably do some magic of storing the desired callback functions from the blueprints into the app itself, then have your `user_claims_loader` look for a list of those functions instead of having them hard coded.

I'm not 100% sure this would work, or if it would actually be any easier to read and maintain then doing some imports and hard coding what you need to, but if that's important to your application it might be worth looking into.
