### ISSUE TITLE
Possible improvement of claims

### ISSUE THREAD

**Issue by Groenbech96** [vimalloc/flask-jwt-extended#164]
Hi! 
I have been looking at the [flask-simple](https://github.com/vimalloc/flask-jwt-simple) vs this for implementing JWT in client-server, as well as inter-process communication (between rest services).
I really like the implementation of claims in flask-simple, and that does not seem possible in this library? 
It would be very nice to have these custom claims (aud, iss, other claims in the [jwt standard](https://tools.ietf.org/html/rfc7519)) available in this library as well! I would like to use this library for the features it offers.  
🥇 The library is so well written! 🥇

**Comment by vimalloc** [comment]
You are correct that it isn't possible at the moment, I wouldn't be opposed to adding some functionality like that though. Maybe an `@jwt.additional_claims` callback method that returns a dictionary that merges with the other claims we are currently adding? We should probably add some checking to make sure any claims returned in that call don't conflict with any of our default claims and cause an expected behavior, but I don't think that would be very hard to do. 

I would be happy to add this myself, but am pretty busy at the moment so I'm not sure exactly when I would have time to get that into the library. If you wanted to submit a pull request to get it setup faster, I would be more then happy to work with you and help get it merged. :+1:

**Comment by Groenbech96** [comment]
Hi! 
That is awesome to hear. I will gladly take a look at it and it sounds like a good approach. 
Do user_claims get obsolete due to the flexibility of additional_claims? That is something that we might want to think about. I will work on a implementation 👍 👍

**Comment by vimalloc** [comment]
Thanks for be willing to tackle this! A couple things:

First, I don’t want user_claims to be obsolete. I think it makes for a simpler abstraction for most use cases, but more importantly I do not want this to be a breaking change :+1:

Second, we will probably need to take care if we want to do some validations on any custom claims there and how they could be passed to the underlying pyjwt decode call.

**Comment by Groenbech96** [comment]
Cool :) 

I have added additional claims alongside the existing user_claims and defaulted the callback not to add any additional claims. If any claims is set in the config 'JWT_ADDITIONAL_CLAIMS', as a list, then  they will have to be added. Tested it with tox, 100% code coverage and added two additional test files for the additional claims.
