### ISSUE TITLE
Issue with  {"msg": "Invalid audience" }

### ISSUE THREAD

**Issue by piotrkakiet** [vimalloc/flask-jwt-extended#169]
Hi, I am trying to run my application using jwt in query string. My payload contains aud and my app coinfig has JWT_DECODE_AUDIENCE property set but somehow flask_jwt_extended doesn't load it hence I get exception thrown in api_jwt.py::_validate_aud in sect```
ion 
        if audience is None and 'aud' in payload:
            # Application did not specify an audience, but
            # the token has the 'aud' claim
            raise InvalidAudienceError('Invalid audience')
```
I am using 

Flask-JWT-Extended -> 3.10.0
PyJWT -> 1.6.4 

Is anyone aware of this issue

**Comment by vimalloc** [comment]
So `JWT_DECODE_AUDIENCE` is not currently an option in this extension. There is some work happening right now that would add support for stuff like that (in https://github.com/vimalloc/flask-jwt-extended/pull/166).

However, if you are consuming tokens created from another application, there is a very strong chance that other claims required for this extension to work will be missing. It is pretty opinionated about what needs to be in a JWT in order to get all the extra features (such as refresh token, fresh/stale tokens, etc) to work.

In that case, flask-jwt-simple may be a better fit for your needs, as it doesn't have any of the opinionated requirements that flask-jwt-extended does. There is a brief comparion between the extension that you can read about here: https://github.com/vimalloc/flask-jwt-extended#when-to-use-flask-jwt-extended
