### ISSUE TITLE
proper way to enable or disable for unittesting

### ISSUE THREAD

**Issue by havok2063** [vimalloc/flask-jwt-extended#171]
This has been deployed and is heavily integrated into my system, for my API. I'm trying to now fix all my tests (pytest) so they can work again after employing authentication.  What is the best way to set up `flask_jwt_extended` with `pytest` and `pytest-flask` so tests will properly run?

**Comment by vimalloc** [comment]
I haven't used pytest-flask before, but for unit tests I've written with this in the past with pytest I created some helper functions to do the requests while injecting a token via the authorization header. You can see some examples of how to do that with pytest and flask here: https://github.com/vimalloc/flask-jwt-extended/blob/master/tests/test_headers.py

**Comment by vimalloc** [comment]
You could also probably utilize the custom decorator stuff to create your own `jwt_required` decorators that inject your own testing token into the request or the decoded token into the `ctx_stack.top.jwt` when a testing environmental variable was set. I haven't done that before and don't know how well it would work, but it might be an options depending on your needs.

http://flask-jwt-extended.readthedocs.io/en/latest/custom_decorators.html

**Comment by slyphon** [comment]
I know this is an old issue, but I came across it googling for solutions to "turning off" jwt in testing.

Just wanted to share the following, I placed this at the top of my test module:

```lang=python
@pytest.fixture(autouse=True)
def neuter_jwt(monkeypatch):
  def no_verify():
    pass

  from flask_jwt_extended import view_decorators

  monkeypatch.setattr(view_decorators, 'verify_jwt_in_request', no_verify)
```
and it worked to disable the `@jwt_required` decorator. You can't directly stub out the decorator, because by the time the tests run, the relevant functions have already been wrapped. This works because it stubs out the method that decorator calls to perform the validation. The monkeypatch will be undone at the end of each test, so it won't have an impact on tests where it isn't used.

Hope this helps someone!
