### ISSUE TITLE
current_user is not cleared before processing another request

### ISSUE THREAD

**Issue by DenerKup** [vimalloc/flask-jwt-extended#176]
The situation: you have 2 endpoints. The first is protected with `@jwt_required`. The second is protected with `@jwt_optional`, but it's behaviour depends on the `current_user` (for example, access rights check). Then admin requests the first endpoint, `current_user` is set to admin. Than request with no auth credentials is passed to the second endpoint, but `current_user` is still happens to be admin. This is a major security issue.

Here user is set to one of the flask's context objects: https://github.com/vimalloc/flask-jwt-extended/blob/master/flask_jwt_extended/view_decorators.py#L163

And here we see that for some reason application context is used to store `current_user`, instead of request context: https://github.com/vimalloc/flask-jwt-extended/blob/master/flask_jwt_extended/view_decorators.py#L7

**Comment by vimalloc** [comment]
That's not how the _app_ctx_stack works. It is a per-request context, and does not persist across separate requests. http://flask.pocoo.org/docs/1.0/appcontext/#lifetime-of-the-context

**Comment by DenerKup** [comment]
Thanks for the fast reply! I were having problems during testing with pytest and that was my fault as I were creating application context for the whole lifetime of the test client.

Anyway, why do you prefer application context over request one?

**Comment by vimalloc** [comment]
Heh, yeah that does sound like a very non-obvious situation you had there, glad you figured out what was going on :+1:

Honestly, the only reason I used the application context when creating this extension was because all the documentation and other extensions I looked at did the same thing. I think everything would work just fine if this used a request context instead of an application one, minus any potential subtle breakage that might occur if users created their own application contexts for whatever reason.
