### ISSUE TITLE
jwt in cookie to be accessed by a protected resource on a POST request

### ISSUE THREAD

**Issue by sridharp2992** [vimalloc/flask-jwt-extended#177]
Hi,

I'm using JWTs for authentication and for accessing my protected end-points. I have a couple of design choices to make and would really appreciate your help here.

If I'm using JWTs for auth and accessing protected resources, do I necessarily need to store the access tokens in cookie and add csrf protection or can I just store the access token in localStorage and pass it with every ajax call as a Bearer Token? Which one would you recommend and why?

Also, to keep in mind, there our application has very high emphasis on security.

If I were to go to the cookie + csrf route, how do I decorate a protected resource - POST method with Jwt-required when POST calls don't work with CSRF enabled?

Am I missing something here?

Thanks & Regards
Priya

**Comment by sridharp2992** [comment]
Thanks for the prompt response.
I guess that's what I'm looking for. Could you direct me on how to pass the CSRF token in the header while doing the post request? I'm guessing we'd do this in the ajax call, similar to the bearer token. But I'm not exactly sure how to do this.

Also, one more question. 
If jwts are a one-stop solution to get user information securely, why would we need to go with a cookie? Doesn't it open up XSS/CSRF vulnerabilities, which is an additional thing to manage?

I'm not sure if I'm missing something here, feel free to correct me if I misunderstood something!

Thanks & Regards
Priya

**Comment by vimalloc** [comment]
You will be vulnerable to XSS either way. The difference is if the JWT is in the localStorage then an XSS attack will allow the attacker to grab the JWTs, whereas if the JWT is in a `httponly` cookie an XSS attack would allow the attacker to make requests as the user, but not actually steal the JWTs for attacks at a later date. You also have the benefit of setting the `secure` flag on the cookie, so that the browser will never send the cookies (and thus the JWTs) to an endpoint that is not secured with https.

The downside to these things is you are now vulnerable to CSRF attacks. You can avoid the CSRF attacks by utilizing double submit verification. In a nutshell you need to grab a special CSRF token and send it in as an additional header in every request you make to the backend. By default there is a cookie that you can get the key from using javascript. You can also send the CSRF token back in your JSON payload in your login/refresh endpoints, and store it in localStorage to be retrieve via javascript when you make the requests. See these links for specifics

* http://flask-jwt-extended.readthedocs.io/en/latest/tokens_in_cookies.html
* http://flask-jwt-extended.readthedocs.io/en/latest/options.html#cross-site-request-forgery-options

**Comment by sridharp2992** [comment]
Hi,
Thanks for your response again.
So, if I want to go the Bearer token way (which is supposed to be more secure than the cookie route as the browser is not attaching the tokens for you automatically), where should I store my access tokens? In other words, httponly cookies won't let me access the tokens from javascript and without accessing the tokens I can't append the bearer token in my jquery. So, what's the safest way to send my protected calls to client-side using bearer tokens? 

And yes, I will be able too send the CSRF token in my JSON payload and validate it against the one in localStorage. That's possible for the CSRF tokens, but how do I deal with the bearer tokens?

Thanks again!

**Comment by vimalloc** [comment]
So you only need the CSRF stuff if you are storing the JWTs in cookies. If you are adding an `Authorization` header to each request that contains the JWT you don't need to do that. In that situation, I would suggest sending your JWTs back in the JSON body of your login endpoint, and store them in local storage, where your javascript can grab them every time you are making an ajax request.

**Comment by sridharp2992** [comment]
Thanks again!
That's exactly what I was thinking. But I'm getting confused here because: 
Cookies with CSRF are safer than Localstorage  
Bearer Tokens are supposed to be safer than cookies as you have control over the request your browser sends (its not automated unlike in cookies); Hence, an attacker won't be able to send requests as the user; But on the downside, like you mentioned, he could grab the jwt from localStorage all together. My access tokens are short-lived though.

I'm not sure if there is a solution that fills the hole in both these cases, I'm also not sure which one is more secure over the other.

If you could throw some light on that front, it would e very helpful!

Also, if I were going the cookie with csrf route, how would me POST request look like? Right now, I'm using Bearer Tokens.

Thanks a lot!

**Comment by vimalloc** [comment]
I think if you want to get super technical, the cookies solution might be just a _little_ bit more secure, assuming one is properly using CSRF protection everywhere. But it's not by a huge amount, I think the headers option would honestly be just fine too from a security point of view. 

If you do want to go the cookies route it's not too complicated. In the default settings, when you make a request you will need to attach an  `X-CSRF-TOKEN: <csrf_token>` header in the request, and the JWT will automatically be sent in as well via the cookie. By default, you can parse out the `csrf_token` using javascript by grabbing it from the `csrf_access_token` cookie or the `csrf_refresh_token` cookie respectively. If you don't want to grab them from the cookie, you can get the `csrf_token` value at the time that you create the JWT, and send it back in the JSON payload, where the browser will then store it in the localStorage. See the very bottom of this page for an example of how that would look with code: http://flask-jwt-extended.readthedocs.io/en/latest/tokens_in_cookies.html

**Comment by sridharp2992** [comment]
I was just looking for that!
Your answers helped a lot.
Thanks very much!
