### ISSUE TITLE
Question about private claims

### ISSUE THREAD

**Issue by karabill** [vimalloc/flask-jwt-extended#186]
I am supporting a back end server which only consumes JWT (thus, I can not influence the creation of the JWTs). The problem is that the JWT that the server receives contains some private claims like this:
```
{
  "exp": 1534854259,
  "identity": "test",
  "hello": "test",
  "foo": [
    "bar",
    "baz"
  ]
}
```

However, I saw in the documentation that the flask-jwt-extended library supports private claims (called user claims), but they are placed under the `user_claims` field, e.g.:
```
{
  "exp": 1534854259,
  "identity": "test",
  "user_claims": {
    "hello": "test",
    "foo": [
      "bar",
      "baz"
    ]
  }
}
```

I also saw that there is a `JWT_USER_CLAIMS` config option that can alter the `user_claims` string.

My question is if it is possible to get private claims that exist in the root of the object, like the `hello` in the first example.

**Comment by vimalloc** [comment]
In this extension you can get that data via the `get_raw_jwt` function, but there will probably other things that break if you try to use this extension with a different token provider. This extension is very opinionated about what claims need to exist in a token in order to get everything to work. For example, it requires a type claim to differentiate between an access and refresh token, and a fresh claim to determine if an access token can be used for specific fresh required endpoints. If using an external provider for the JWTs, you probably want to use the sister extension to this one, flask_jwt_simple. It was designed for that use case from the get go.

**Comment by karabill** [comment]
Thanks for the reply and the suggestion. It was helpful.
