### ISSUE TITLE
Flash messages are flashed only upon redirect

### ISSUE THREAD

**Issue by sridharp2992** [vimalloc/flask-jwt-extended#190]
Hello,

I'd like to be able to flash messages asynchronously on my web page. I think the flash messages are designed to be display upon redirect. If I don't have a redirect and want to display messages real time, how do I go about it?

Like for example, I'm using a celery task to trigger an email. 
In my back end code, I have included a line of code to flash a message upon completion of the celery task. But its only getting display when I logout and not real-time. In fact, all my flash messages inside a protected endpoint are getting displayed when I logout all at once.
I'm not sure what I'm missing here! 

Your suggestions would be very helpful!

Thank you!

**Comment by vimalloc** [comment]
This is not related to flask-jwt-extended. How you flash your message will entirely depend on how your backend is configured to pass this information along, and how your frontend is configured to receive and display said information. Because this is unrelated to this extension I'm going to close this issue.

That said, if you are looking for real time updates to your frontend based on some long running task in your backend, you might want to check out web sockets to communicate that information between the backend and frontend. Alternately, you could have your frontend `poll` for new updates (via ajax requests) and flash a message once there is new data provided there. Hopefully this will give you some ideas on how to handle this :+1:
