### ISSUE TITLE
Make it possible to override the current user

### ISSUE THREAD

**Issue by libre-man** [vimalloc/flask-jwt-extended#206]
Sometimes it is useful to override the current user for an application. It seems this isn't possible, except for manually changing the `_app_ctx_stack`. It would be really nice if there was a special method to do this.

**Comment by vimalloc** [comment]
Are you wanting this for masquerading as another user or something else? I don’t know how that could be safely done at this extensions level except by creating a new JWT for each request, as someone might have some custom claims in their tokens that are needed for their endpoints. And creating a new JWT for each request sounds not so great to me. If that is the problem you are trying to solve, my initial thought is that it would probably make more sense to handle it in the frontend of your application instead of something built into this extension.

**Comment by libre-man** [comment]
That is not exactly what I want. My use case is when hiding some sensitive data in the serialization layer (like emails). My login endpoint returns the serialized user that just logged in, however as the request didn't contain a JWT token (it couldn't, as it is just logging in) their email gets filtered. So after creating a new token I want to use that token as the token of the request. Currently I solve this by just setting `_app_ctx_stack.top.jwt_user` with the just logged in user. However, it would be nice if my code could just call a function like `set_current_user(user)` that sets `flask_jwt.current_user` to the given user.

**Comment by vimalloc** [comment]
So at the point you are wanting to do this a token has already been created for the user, and you are wanting to set the current user to this newly created data so that you can call other functions in the same request that the user logged in with?

I don't see anything fundamentally wrong with that. It might be easier to pass the user in as an argument to your helper functions instead of using `current_user`, so that they aren't relying on global state and thus easier to unit test, but obviously I haven't seen your application so I don't have a complete picture of what your trying to do.

I'm pretty strapped for time right now, if you do want to go this way would you be willing to throw together a pull request for this feature? It would be adding the code with documentation in this file (https://github.com/vimalloc/flask-jwt-extended/blob/master/flask_jwt_extended/utils.py) then updating https://github.com/vimalloc/flask-jwt-extended/blob/master/docs/api.rst#utilities to export that documentation for that function.

Thanks :+1:
