### ISSUE TITLE
Decode token that has expired

### ISSUE THREAD

**Issue by danny305** [vimalloc/flask-jwt-extended#220]
It would be nice to be able to decode and grab the claims (and identity) from either an access token or refresh token that has expired so that information could be utilized. Something like jwt.decode(token, verify_exp=False) would be useful. 

We discussed this: https://stackoverflow.com/questions/54106546/flask-jwt-extended-current-user-identity-none-when-creating-non-fresh-access-t

**Comment by vimalloc** [comment]
Thanks for opening this issue. I was thinking about it more the other day, and instead of providing a helper function for that, I think it be easier to pass the dictionary of the expired token to the `@jwt.expired_token_loader` callback function, so that people can modify how they want that to work in an intuitive way.

We could implement this with depreciation warning without making a breaking change the same way that we handled things in #212.

**Comment by vimalloc** [comment]
Yep. It hasn’t been merged yet, but an example of what I’m planning can be seen here: 
https://github.com/vimalloc/flask-jwt-extended/pull/221/files#diff-9570d0b23c3cb956412b9193933415b2

I’ll update this ticket when I have that merged and a new release cut.

**Comment by danny305** [comment]
Is there a reason that in the expired token loader callback you don't have a keyword argument to refresh the token automatically if the client has a valid refresh token? Also, what is the reason that these callback functions aren't written as 1 class so we could just create a subclass and be able to modify individual loader callbacks as need? I am interested in your reasoning.

**Comment by vimalloc** [comment]
This has been released in version 3.16.0.

Cheers.

**Comment by danny305** [comment]
Thank you.
