### ISSUE TITLE
JWT token and concurrent sessions

### ISSUE THREAD

**Issue by ctippur** [vimalloc/flask-jwt-extended#230]
Hello,

I am seeing some weirdness around JWT token usage.
If the same user credentials are used to generate tokens from different locations, one of the user gets a 500 internal server error.

I see the below entries in the logs. Wondering if this is a known behavior? Is there anyway to mitigate it?

File "/var/task/flask_jwt_extended/config.py", line 58, in jwt_in_cookies
return 'cookies' in self.token_location
File "/var/task/flask_jwt_extended/config.py", line 44, in token_location
locations = current_app.config['JWT_TOKEN_LOCATION']
KeyError: 'JWT_TOKEN_LOCATION'

**Comment by vimalloc** [comment]
I haven't seen that before, but if I had to guess I think that a flask `app` wasn't registered with this extension, by either doing one of:

 ```python
jwt = JWTManager(app)
# or
jwt = JWTManager()
jwt.init_app(app)
```

If that's not the case, if you can provide a minimal, complete, and verifiable example that demonstrates this problem, I would be happy to look through it and try to figure out whats going on.

**Comment by ctippur** [comment]
Landon,
I use connexion and deploy the app on aws using Zappa.
The issue is that this happens intermittently. For the most part, I can login and the workflow is as expected. However, I have seen that if I have logged in as the same user (different active tokens), I seem to hit this error.

```
from flask_jwt_extended import (
    JWTManager, jwt_required, create_access_token,
    get_jwt_identity, get_jwt_claims
)

@jwt_required
@validate
def billing_subscription_id_get(SubscriptionId):
    return 'do some magic!'
```

Here is how it is initialized

```
    def __init__(self, f):
        self.f = f
        self.user_group=None
        # Create logger
        self.logger = logging.getLogger(__name__)

    def __call__(self, *args, **kwargs):
        function_name = self.f.__name__
        app = current_app
        app.config['JWT_SECRET_KEY'] = 'BLAH'  # Change this!
        app.config['JWT_TOKEN_LOCATION'] = ['cookies', 'headers']
        jwt = JWTManager(app)

        ## Authentication and authorization
        authorization = connexion.request.headers.get('Authorization') or None
        current_user = get_jwt_identity()
        claim = get_jwt_claims()
```

**Comment by vimalloc** [comment]
I'm not sure what's going on there with those other frameworks, but the `KeyError` you are seeing via `current_app.config['JWT_TOKEN_LOCATION']` is set as a flask default config value whenever the extension is initialize with a flask application (https://github.com/vimalloc/flask-jwt-extended/blob/master/flask_jwt_extended/jwt_manager.py#L155). Since you are seeing that key error, I'm almost positive that something is happening that prevents `jwt = JWTManager(app)` from being run in some case, or a different `app` is being used in a request that `JWTManager` was not initialized with. A race condition or something perhaps? 

I would suggest making sure your flask and flask-jwt-extended packages are up to date. Unfortunately, besides this I don't know what to suggest. If you're able to create a way to reproduce this locally I could maybe look closer into it. That said, there is extensive unit testing and real world usage with flask-jwt-extended, and I highly doubt the error you are seeing is stemming from a bug in flask or this extension.

Sorry I can't be of more help here.

**Comment by ctippur** [comment]
Landon,

Thanks for responding. I am unable to reproduce it in my local environment.
Can you give me any pointers on how I can possibly troubleshoot this issue?
This app is being run on AWS Lambda. 
Appreciate any pointers.
I will ensure I have the latest version.

Shekar

**Comment by vimalloc** [comment]
Sorry I haven't gotten back to you sooner, life has been super hectic this past week.

I think the first thing I would do in this situation is log `app.extensions['flask-jwt-extended']` on your incoming requests. If that is empty in the same requests that you are seeing the error in, it would verify that the `app` you are using didn't have `flask-jwt-extended` initialized with it. Hopefully from there, you could grab a stack trace or something to help narrow down what is going on.

Let me know if you have any other questions, and good luck getting that resolved.

**Comment by ctippur** [comment]
Landon,

Sorry about the delay in responding. I have upgraded the packages to the latest version. I still see the same error:
Looks like the error is due to some config issue. 
```if config.jwt_in_cookies:
File "/var/task/flask_jwt_extended/config.py", line 58, in jwt_in_cookies
return 'cookies' in self.token_location
File "/var/task/flask_jwt_extended/config.py", line 44, in token_location
locations = current_app.config['JWT_TOKEN_LOCATION']```

My app config is just pointing to headers now.  Wondering if this could be a issue?
app.config['JWT_TOKEN_LOCATION'] = ['headers']

Here is the complete stack trace:
```
Traceback (most recent call last):
File "/var/task/flask/app.py", line 1982, in wsgi_app
response = self.full_dispatch_request()
File "/var/task/flask/app.py", line 1614, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/var/task/flask/app.py", line 1517, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/var/task/flask/_compat.py", line 33, in reraise
raise value
File "/var/task/flask/app.py", line 1612, in full_dispatch_request
rv = self.dispatch_request()
File "/var/task/flask/app.py", line 1598, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/var/task/connexion/decorators/decorator.py", line 48, in wrapper
response = function(request)
File "/var/task/connexion/decorators/uri_parsing.py", line 143, in wrapper
response = function(request)
File "/var/task/connexion/decorators/validation.py", line 347, in wrapper
return function(request)
File "/var/task/connexion/decorators/produces.py", line 38, in wrapper
response = function(request)
File "/var/task/connexion/decorators/parameter.py", line 126, in wrapper
return function(**kwargs)
File "/var/task/swagger_server/controllers/default_controller.py", line 269, in c_name_clinic_name_get
res=cl_name_clinic_name_get(ClinicName)
File "/var/task/flask_jwt_extended/view_decorators.py", line 100, in wrapper
verify_jwt_in_request()
File "/var/task/flask_jwt_extended/view_decorators.py", line 29, in verify_jwt_in_request
jwt_data = _decode_jwt_from_request(request_type='access')
File "/var/task/flask_jwt_extended/view_decorators.py", line 226, in _decode_jwt_from_request
if config.jwt_in_cookies:
File "/var/task/flask_jwt_extended/config.py", line 58, in jwt_in_cookies
return 'cookies' in self.token_location
File "/var/task/flask_jwt_extended/config.py", line 44, in token_location
locations = current_app.config['JWT_TOKEN_LOCATION']
KeyError: 'JWT_TOKEN_LOCATION'
```

**Comment by vimalloc** [comment]
Yeah, that sounds like the same thing I was talking about above. I still think that `jwt.init_app(app)` or `JWTManager(app)` is not being called somewhere, or not called before a request comes in on `current_app`, otherwise that config option would exist on the current_app.

**Comment by ctippur** [comment]
The issue is 95 % of the requests go through fine.

**Comment by vimalloc** [comment]
Sure. Maybe a race condition or something? Because the only other explanation I could think of would be a bug in core pythons dictionary implantation of [setdefault](https://docs.python.org/3/library/stdtypes.html#dict.setdefault), which is parent class for flasks [current_app.config](https://github.com/pallets/flask/blob/a74864ec229141784374f1998324d2cbac837295/flask/config.py#L40) and initialized in this extension on the [jwt.init_app](https://github.com/vimalloc/flask-jwt-extended/blob/master/flask_jwt_extended/jwt_manager.py#L155) call. The chances of that being the case seem slim to none.

**Comment by ctippur** [comment]
I doubt that as well. Going back to the theory of wrong initialization of app - if this were to be the case, shouldn't I get an error for every call?
Here is how I am initializing the app.

```
#!/usr/bin/env python3
import connexion
import sys
import os
from encoder import JSONEncoder
from flask_cors import CORS, cross_origin


app = connexion.App(__name__, specification_dir='./swagger/')

app.app.json_encoder = JSONEncoder
app.add_api('swagger.yaml', arguments={'title': 'Test'})
CORS(app.app)


if __name__ == '__main__':

    app.run()
```

**Comment by vimalloc** [comment]
Based on one of your above comments it looks like JWTManager is being initialized during some `__call__` method instead of before `app.run()` is called. That's why I think it might be a race condition on when your app is initialized vs when a request come in. But that is still just a guess, I'm not familiar enough with the libraries you are using to know what they are doing behind the scenes. 

What happens if you move the JWTManager to this file instead? Something like:

```python
#!/usr/bin/env python3
import connexion
import sys
import os
from encoder import JSONEncoder
from flask_cors import CORS, cross_origin
from flask_jwt_extended import JWTManager

app = connexion.App(__name__, specification_dir='./swagger/')    
app.config['JWT_SECRET_KEY'] = 'BLAH'  # Change this!
app.config['JWT_TOKEN_LOCATION'] = ['cookies', 'headers']
jwt = JWTManager(app)

app.app.json_encoder = JSONEncoder
app.add_api('swagger.yaml', arguments={'title': 'Test'})
CORS(app.app)

if __name__ == '__main__':
    app.run()
```

**Comment by ctippur** [comment]
Landon, 
I think I am able to reproduce it.
I restarted the server on my laptop and had retained the old token. Looks like this scenario throws the error.
Looks like the same scenario happens on a serverless environment like AWS Lambda. The containers running Lambda would restart and invalidate the token. 
Would this mean that it is not feasible to use JWT token on a container environments like Lambda?
Shekar

**Comment by vimalloc** [comment]
What? No, that’s not how JWT or this extension work at all. The server doesn’t store the token at all so there is nothing to invalidate. The only way a token can be invalidated after being created is if the secret key used to sign it is changed, the token is expired due to how long ago it was created, or if you explicitly setup a blacklist in your backend and use that to mark a token as revoked. You could start, stop, and restart your server, spin up a server in a new location, etc, and as long as the above hold true the same token will work on any of them. 

Now if you are seeing the same `KeyError` after restarting your server, that means that the flask app is being recreated in such a way that the `JWTManager` is not being initialized after the restart happens. The stacktrace is telling us in no uncertain terms that this is the issue you are seeing. If you can provide some sample code for how to duplicate this and the reproduction steps (like the exact commands you are using to restart the server) I would be more then happy to see if I can help fix this with you. But as it stands, everything is pointing towards an issue with how the extension is being used, not the extension itself, and I don’t know what other advice I can provide besides what I’ve already outlined above.

**Comment by pagreene** [comment]
Hi @vimalloc, our team is looking at using Flask-JWT-Extended on our serverless architecture and this is a concern for us as well. After reading the above, the point on which I am not clear is where does Flask-JWT store the JSON Web Tokens. I am new to JWT, so perhaps I am missing a beat here, but as I understand it, you would need to store a copy of the token on the server side, hashed, to compare with incoming tokens. If so, then Flask-JWT-Extended must store them somewhere, and given that the config (as far as I can tell) doesn't have options for using a database, that would indicate they are stored locally, which as Shekar mentioned, would not work on a serverless architecture, where each request is effectively handled by a "new" server. Thus how could this be true:
>  You could start, stop, and restart your server, spin up a server in a new location, etc, and as long as the above hold true the same token will work on any of them.

I apologize if I'm missing something obvious.

**Comment by vimalloc** [comment]
> but as I understand it, you would need to store a copy of the token on the server side

@pagreene That is fundamentally incorrect. JWTs are part of the class known as stateless authentication. In broad terms, it works by hashing the contents of your token with a secret key or passphrase, and adding that as a signature to the JWT. A good overview of this can be seen here (https://jwt.io/introduction/), but in practice this means is that as long as your servers have the same secret key, and that secret key actually remains a secret, then they are able to validate that a JWT was created by you and hasn't been tampered with, without the need for storing any information on the server.
