### ISSUE TITLE
Setting custom claims with parameters

### ISSUE THREAD

**Issue by kwagdy** [vimalloc/flask-jwt-extended#237]
In the example from docs [Custom Decorators](https://flask-jwt-extended.readthedocs.io/en/latest/custom_decorators.html) to set custom claims: 
```
@jwt.user_claims_loader
def add_claims_to_access_token(identity):
    if identity == 'admin':
        return {'roles': 'admin'}
    else:
        return {'roles': 'pesant'}
@app.route('/login', methods=['POST'])
def login():
    username = request.json.get('username', None)
    access_token = create_access_token(username)
    return jsonify(access_token=access_token)
```

In the function definition it is mentioned that
> user_claims_loader(callback)[source] This decorator sets the callback function for adding custom claims to an access token when create_access_token() is called

If I understand correctly, every time _create_access_token_ is called the user_claims_loader call back function will be called to set the required custom claims. What if we need to pass a few claims other than the user identity? If only 'identity' can be passed to _add_claims_to_access_token_ then those parameters are assumed to be already part of the _identity_ object? 

Also in the above example `create_access_token(username)` sends **username**, yet in the `add_claims_to_access_token` a test was done for an identity state being **admin** or not!? Am I missing something or was this a typo?

The question here is where it is possible to add custom claims by passing those claims to the _user_claims_loader_ callback function, rather than passing the user (_or as stated above username_) token. If the properties are already part of the user, why add them to the custom claims as well?

**Comment by vimalloc** [comment]
There are two ways around this. First, you can actually pass in a python object as the identity (which is then passed to the user_claims_loader), and then specify another decorated function (`@jwt.user_identity_loader`) to pull out the identity for that python object. This is documented here: https://flask-jwt-extended.readthedocs.io/en/latest/tokens_from_complex_object.html

The other option is to use the `user_claims` kwarg to create_access_token instead of using `user_claims_loader`. This is documented here: https://flask-jwt-extended.readthedocs.io/en/latest/api.html#flask_jwt_extended.create_access_token

If either of those docs are confusing or were hard to find or anything, I would more then welcome pull requests to help improve them :+1:

Cheers.
