### ISSUE TITLE
jwt_optional borks on expired token

### ISSUE THREAD

**Issue by ajbraus** [vimalloc/flask-jwt-extended#286]
Hi there, great library but I'm wondering about the logic of making `jwt_optional` not work when a token is expired. 

Imagine I want people to see the same page one way if they are logged in, and another way if they are not. Why not let me visit the end point, expose the JWT token, and then have the get_jwt_identity return `None` if the token is expired?

Perhaps I'm just doing things all backwards. A good example of how you would make an endpoint truly optional if you are logged (not optional except if a token is expired) would be very useful.

**Comment by vimalloc** [comment]
This was an intentional choice, but it's easy enough to work around using a custom decorator (https://flask-jwt-extended.readthedocs.io/en/stable/custom_decorators/). Something like this should allow you to treat an expired token as no token:

```python
from flask_jwt_extended import verify_jwt_in_request_optional
from jwt import ExpiredSignatureError

def custom_jwt_optional(fn):
    @wraps(fn)
    def wrapper(*args, **kwargs):
        try:
            verify_jwt_in_request_optional()
        except ExpiredSignatureError:
            pass
        return fn(*args, **kwargs)
    return wrapper
```

**Comment by vimalloc** [comment]
I realize I didn't mentioned why it is was done this way in my last comment. If someone is using a refresh token, we want them to be able to use the same workflow for refreshing an expired token on all protected endpoints. If jwt_optional didn't raise an expired token error, you would need to have some custom logic for when to use your refresh token for each jwt_optional endpoints instead of looking at the http status code and acting accordingly.

I'm going to close this out for now, if the custom decorator doesn't solve this for you, feel free to reopen the issue.
