### ISSUE TITLE
This code does not catch any error that might happen inside an custom expired token handler function

### ISSUE THREAD

**Issue by RonsenbergVI** [vimalloc/flask-jwt-extended#288]
@app.errorhandler(ExpiredSignatureError)
        def handle_expired_error(e):
            try:
                token = ctx_stack.top.expired_jwt
                return self._expired_token_callback(token)
            except TypeError:
                msg = (
                    "jwt.expired_token_loader callback now takes the expired token "
                    "as an additional parameter. Example: expired_callback(token)"
                )
                warn(msg, DeprecationWarning)
                return self._expired_token_callback()

**Comment by RonsenbergVI** [comment]
This can be confusing for debugging but nothing major I guess - might be obvious but just in case

**Comment by vimalloc** [comment]
Thanks for checking, it is intentionally designed that way. If someone had a bug that raised an exception in their custom handler, I would rather have them get a stacktrace pointing back to their bug instead of falling back to the default implementation or something along those lines. That could lead to much larger problems :+1:
