### ISSUE TITLE
Flask jwt Identity Method 

### ISSUE THREAD

**Issue by diegovini** [vimalloc/flask-jwt-extended#30]
Hi, I´m a user of Flask JWT and I´ve been trying to understand more about this extended version.

Right now, we need to send a key in the same JSON that contains the access_token key. I could not find a easy way to do this using the regular Flask-JWT.

Looking at your extended version, I could not find a methodlike  the "identity" method used in flask-jwt.

We are using this method to check the payload against our database, so only after that, the resource will be avaliable for the user. 
( authenticate method creates the token -- identity method gets the payload and verify it against our db)
How can we do that using your version?

We´re new to this, so maybe we´re missing some things here hehe

**Comment by vimalloc** [comment]
You can use the ```get_jwt_identity()``` function for that. You can see an example of this in action under the protected view here: http://flask-jwt-extended.readthedocs.io/en/latest/basic_usage.html

There is a similar function which can be used for accessing any custom claims added to the jwt, ```get_jwt_claims()```. An example of that in action can be found here: http://flask-jwt-extended.readthedocs.io/en/latest/add_custom_data_claims.html

Let me know if that doesn't answer your question.

Cheers!

**Comment by diegovini** [comment]
I´ve read that yesterday. but maybe I´m missing something here!

From what I remember, I had to write the Identity method only once, and everytime a method had a @jwt_required, it would then check the identity method by itself.

In the example you mentioned, I can get the token payload by calling the get_jwt_identity(). 

But, do I have to do it every single time I have a protected resource? 
In flask-jwt,  I only had to use the decorator (jwt_required()) and the identity method was called.

I forgot to mention I´m using flask_restful as well.

**Comment by vimalloc** [comment]
You are correct, by default we do not do any sort of user loading on a jwt_required. This was an intentional choice, we wanted to allow users to not take the database lookup hit when accessing an endpoint that isn't using data from the database, to help speed things up. 

That said, it should be pretty easy to mimic this functionality via an additional decorator. I updated this example (http://flask-jwt-extended.readthedocs.io/en/latest/tokens_from_complex_object.html) to show you one way this might be implemented:

```python
from functools import wraps
from flask import Flask, jsonify, request, g
from flask_jwt_extended import (
    JWTManager, jwt_required, create_access_token,
    get_jwt_identity, get_jwt_claims
)

app = Flask(__name__)
app.secret_key = 'super-secret'  # Change this!

# Setup the Flask-JWT-Extended extension
jwt = JWTManager(app)


# This is a simple example of a complex object that we could build
# a JWT from. In practice, this will normally be something that
# requires a lookup from disk (such as SQLAlchemy)
class UserObject:
    def __init__(self, username):
        self.username = username
        if username == 'test':
            self.roles = ['admin']
        else:
            self.roles = ['underlying']


# This method will also get whatever object is passed into the
# create_access_token method, and let us define what the identity
# should be for this object
@jwt.user_identity_loader
def user_identity_lookup(user):
    return user.username


# This is a decorator that can be used to load the user
def user_loader(fn):
    @wraps(fn)
    def wrapper(*args, **kwargs):
        username = get_jwt_identity()
        user = UserObject(username=username)
        if not user:
            # This is where you would handle the error case of a user not loading
            return jsonify({"msg": "user not found"}), 404

        # Store the user so you can use it in your endpoints
        g.user = user
        return fn(*args, **kwargs)
    return wrapper


@app.route('/login', methods=['POST'])
def login():
    username = request.json.get('username', None)
    password = request.json.get('password', None)
    if username != 'test' or password != 'test':
        return jsonify({"msg": "Bad username or password"}), 401

    # Create an example UserObject
    user = UserObject(username='test')

    # We can now pass this complex object directly to the
    # create_access_token method. This will allow us to access
    # the properties of this object in the user_claims_loader
    # function, and get the identity of this object from the
    # user_identity_loader function.
    access_token = create_access_token(identity=user)
    ret = {'access_token': access_token}
    return jsonify(ret), 200


@app.route('/protected', methods=['GET'])
@jwt_required
@user_loader
def protected():
    # You wouldn't have to store this in flask.g, you could put it directly
    # _app_ctx_stack and create a proxy to access it from there, which is
    # what flask_jwt does
    user = g.user
    return jsonify({'user is': g.user.username, 'roles are': g.user.roles}), 200

if __name__ == '__main__':
    app.run()
```

This gives you a user_loader decorator, which stores the loaded user in the flask g object, or returns an error if the user doesn't exist in the database. Note that you don't have to store the user in the flask g object, you could also store it on the _app_ctx_stack directly, and create a proxy object for accessing it. This is what flask_jwt does, and would give you the same behavior that you're used to.

I'm sure you could also do some magic to combine the ```@jwt_required``` decorator and ```@user_loader``` decorator into a single decorator, and use that to access your protected endpoints.

Let me know if this helps, or if I can answer any other questions for you.

Cheers!
