### ISSUE TITLE
Got Internal server error 500 instead of 401

### ISSUE THREAD

**Issue by vvksahoo** [vimalloc/flask-jwt-extended#308]
Hi , i am using flask-jwt-extended for jwt authentication .  I want to validate auth token at middleware of my application . 

```
from flask_jwt_extended import verify_jwt_in_request
# middleware
@app.before_request
def before_request_callback():
    """
        This is callback will run before each and every endpoint .
        Auth layer is defined here .
    :return:
    """
    # Checking jwt-authentication for every request 
        verify_jwt_in_request()
```
In my local if i will hit my api with auth token , its working fine . If i will remove some characters from token it will show 'Invalid-token' which is correct . When deployed on kubernets for the same case getting 500 'internal server error' with 'jwt.exceptions.ExpiredSignatureError: Signature has expired' this error .Please suggest here .

**Comment by vimalloc** [comment]
Normally when I see this behavior it's due to another flask extension breaking flask error handlers. Take a look at this comment (https://github.com/vimalloc/flask-jwt-extended/issues/86#issuecomment-519347386) and see if that holds a resolution for you :+1:

**Comment by vvksahoo** [comment]
Hey sorry for late reply , i have gone through that link and add ```app.config['PROPAGATE_EXCEPTIONS'] = True ``` in config  its works fine. But i am not sure that we should have this on production . For development we do DEBUG = True so  implicitly sets PROPAGATE_EXCEPTIONS to True   For production we do DEBUG = False so PROPAGATE_EXCEPTIONS =False also . So i am confused here weather to use PROPAGATE_EXCEPTIONS or not .

**Comment by vimalloc** [comment]
You could see if this would work instead of the propagate exceptions stuff. I haven't tested it, so I can't speak really speak to it: https://github.com/vimalloc/flask-jwt-extended/issues/141#issuecomment-569524817

To be clear, the `PROPAGATE_EXCEPTIONS` is just a work around, it's not something I love. But the bug for this is part of the flask-restful package (https://github.com/flask-restful/flask-restful/issues/796) so there isn't much I can do about it from my end. If you decide to not use flask-restful package then there would be no need for the work around.
