### ISSUE TITLE
KeyError: 'csrf'

### ISSUE THREAD

**Issue by traubas** [vimalloc/flask-jwt-extended#31]
when trying to use create_access_token
i get an error 
KeyError: 'csrf'

referring to:
```

def _get_csrf_token(encoded_token):
    secret = _get_secret_key()
    algorithm = get_algorithm()
    token = _decode_jwt(encoded_token, secret, algorithm)
    return token['csrf']
```

im running the app on my localhost.
i'm pretty much following the jwt_in_cookie example

any suggestions?

**Comment by vimalloc** [comment]
Are you using the newest version of this extension (1.3.0)? Do you have both  ```app.config['JWT_TOKEN_LOCATION'] = ['cookies']``` and ```app.config['JWT_COOKIE_CSRF_PROTECT'] = True``` set? I have a suspicion that this is due to the ```create_*_token``` methods looking for both of these values, but the ```set_*_cookies``` method is only looking for one of them.

If this does turn out to be the case, I can push an update today to fix that, and raise a more helpful exception in this state instead.

Thanks for the report!

**Comment by traubas** [comment]
oh god you're correct.
i knew it's something with these commands but
it's because i tried to set these configurations in an external file.
maybe i didn't import it right or something.

anyway thanks a lot!

**Comment by vimalloc** [comment]
No problem. I'll try and get an update out in the next couple days that raises a better error in these situations, to help people out in the future.

Thanks for the report :+1:
