### ISSUE TITLE
Revoke all tokens by admin

### ISSUE THREAD

**Issue by robalvsan** [vimalloc/flask-jwt-extended#326]
How it will be the most appropriated procedure to revoke all the tokens a server has already stored, by the admin of the application.

According to the documentation (https://flask-jwt-extended.readthedocs.io/en/latest/blacklist_and_token_revoking/) it seems to be only the possibility of revoking the token by the user itself, but what if the admin of the application, wants to revoke a user's token or even all user's tokens?

**Comment by vimalloc** [comment]
This library makes no assumptions about how you store blacklisted tokens, it is entirely up to your application to figure out what makes sense. Here are some ideas that you might consider:

* Store created tokens in a database, which you can then run queries on to revoke some or all tokens as needed: https://github.com/vimalloc/flask-jwt-extended/tree/master/examples/database_blacklist
* Instead of revoking a JWT, use the `user_loader_callback_loader` to see if the current user is still active, and handle this at the application logic level instead of at the JWT level.
* Use the `encode_key_loader` and `decode_key_loader` to  use a different secret key for a subset of JWTs. Then changing the secret key for those subset of users would automatically invalidate all active tokens they had.
