### ISSUE TITLE
How to Achieve unique access token user  in REST API using JWT extended ? 

### ISSUE THREAD

**Issue by raunaksingh321** [vimalloc/flask-jwt-extended#343]
I am a new to python and trying to build a flask app which will be used as REST Api .

I am stuck on situation where I want only unique user to send access token  means suppose user X login and generated the token .
Then if he passed the token to person Y on different machine ,while the token is active then Y can easily access our REST API .

Will csrf_token_cookie or session cookie will be helpful in these cases ?

How to achieve this ?

**Comment by vimalloc** [comment]
> Will csrf_token_cookie or session cookie will be helpful in these cases ?

No, in fact this is not really feasible using a standard website.

Whenever a web browser makes and HTTP request to a server, it needs to send in some data so the client can be verified. That can be a JWT, a signed cookie, some data that allows looking up a server side session, etc. If that data is ever passed to another user, they would be able to use it and the server would be none the wiser. In a traditional website this will always be the case, because there is no persistent connection between the server and the client, and the server only has access to whatever data the client sends it.

If you *really* need something like this (which I *really* don't recommend), you could perhaps do something like save the IP address of the user in the JWT and compare the IP in the JWT to the current requests IP address, and kick the token out if they don't match. This has several shortcomings, like IP addresses changing due to a DHCP lease ending or switching from mobile to wifi, and wouldn't prevent different users behind the same NAT from sharing tokens.

You could also look into using websockets instead of a traditional website, but that comes with a whole other can of worms that may or may not fit the bill for whatever your use case is.
