### ISSUE TITLE
creating and verifying multiple tokens at multiple locations

### ISSUE THREAD

**Issue by bbbart** [vimalloc/flask-jwt-extended#351]
If I interpret http://www.redotheweb.com/2015/11/09/api-security.html correctly, my frontend and backend communication should use tokens in storage/headers and in cookies at the same time. One is to protect against XSS and the other to protect against CSFR.

I figured that creating two (different) tokens and passing them both to the client in different locations upon authentication is no problem, but according to the docs, `JWT_TOKEN_LOCATION` accepts a list, but is the extension is happy with *any* location providing a valid token, not requiring *all* configured locations to have a valid token.

Am I right? And if so, is this something that still can be forced somehow?

**Comment by vimalloc** [comment]
That is a form of double submit token verification. This extension provides support for the same underlying idea for security, but does it in a sighting different way by having the double submit value be a unique identifier instead of the entire token itself. You can read about how it is implemented in this extension here: https://flask-jwt-extended.readthedocs.io/en/stable/tokens_in_cookies/

**Comment by bbbart** [comment]
Aha! I feel stupid now, seeing that the docs reference the exact same article. :+1: 

Wonderful to see that this seems to be supported already. Let me dive into docs and code again.

Thank you so much for your prompt reply.
