### ISSUE TITLE
[Question] How to verify multiple access_token?

### ISSUE THREAD

**Issue by nvlong198** [vimalloc/flask-jwt-extended#354]
I have 2 access tokens in Header. 
`-H "Authorization: Bearer $ACCESS1, Bearer $ACCESS2" ` , where :
- $ACCESS1 encode by **ES256** and verify by public_key
- $ACCESS2 encode by **HS256** and verify by secret_key

How can I verify both of them?
Thank you.

**Comment by vimalloc** [comment]
You could manually decode a token instead of using the `@jwt_required` decorator, but I strongly recommend not doing this. What would happen if the tokens belonged to two different users? That could cause all sorts of problems in this extension, for example which user would `current_user` point to? Why are you sending multiple JWTs in a single request in the first place?

**Comment by nvlong198** [comment]
**$ACCESS1** is the third party token, refresh every 60 min.
**$ACCESS2** is the token in my app,  I generate base on `current_user` in **$ACCESS1**  and store role/permissions to **$ACCESS2**. 
Should I place them in different headers?

**Comment by vimalloc** [comment]
If you need two different tokens for your app I think storing them in different headers is a great idea. :+1:
