### ISSUE TITLE
Add separate setting for refresh token location

### ISSUE THREAD

**Issue by jrast** [vimalloc/flask-jwt-extended#381]
Would it be possible split the `JWT_TOKEN_LOCATION` configuration in two configurations: `JWT_TOKEN_LOCATION` and `JWT_REFRESH_TOKEN_LOCATION`? 

In my application the refresh token is stored in a cookie (with httpOnly) while the access token is expected to be in the header (Authorization: Bearer <token>). 

I don't know if this is good practice, but in my opinion it's not safe to store the refresh token in any place which is accessible through javascript.

**Comment by vimalloc-mavenlink** [comment]
We actually addressed this in a different way in the forthcoming `4.0.0` version via #373. In this release you can specify the token type and location in each individual route via something like `@jwt_required(locations=['cookies', 'headers'])`.

I have a few minor cleanups to take care of before 4.0.0 can be officially released, the biggest one being updating the documentation and changing blacklist/whitelist to blocklist/allowlist, but besides that the code on the `4.0.0` branch is basically good to go. I could probably get an alpha release out at some point, or you could point your requirements file to that branch directly if you wanted to try out that feature ASAP.

Related, if you ore anyone else wants to help push the 4.0.0 release forward I would always appreciate the help. Feel free to reach out on discord and we could coordinate :+1:

**Comment by jrast** [comment]
Indeed, looks like `4.0.0` will fix this. Looking forward for the release then!

**Comment by DorskFR** [comment]
Same issue here and will be happy to use 4.0.0 when available. 

I configured the refresh token in an HttpOnly cookie and the access token to be stored in memory on the front side and sent in the header.

Problem is when using `@jwt_refresh_token_required` it is actually the access token in headers which is read and this triggers an error token expired.

I noticed this because the refresh would work when I reload the page, effectively clearing the access token stored in memory and allowing the call to go through.

My workaround has been to remove the access_token from the headers only for the refresh call and then there's only the cookie to be checked and it goes through.
