### ISSUE TITLE
RuntimeError: You must provide a `@jwt.user_lookup_loader` callback to use this method

### ISSUE THREAD

**Issue by pipozzz** [vimalloc/flask-jwt-extended#395]
After upgrade I renamed that callback and updated parameters, but still getting this error.
I use factory design so I have separate module with extensions which is imported and in create_app function I init all imported extensions. callback is directly in models.py it was working before upgrade any ideas how to solve this issue? 

Thanks

**Comment by vimalloc** [comment]
Can you provide some code that shows this behavior? Without seeing an example it's hard to say what the problem is. Maybe you have the `route` and `jwt_required` decorators in the wrong order, or maybe you accidently have multiple `jwt` instances and the one you registered the callback function to is a different one then is being used when a request comes in?

**Comment by pipozzz** [comment]
in the meanwhile I resolved my issue, the main causes was using @jwt_required without () I've never had problem like, have you had similar problem with decorators ? btw I use flask-smorest for creating API with arg and response valiadation using marshamllow

Problematic code:  
 ```python
@ads.response(201, AdSchema)
@ads.arguments(AdSchema)
@jwt_required
def post(self, data):
    pass
```

Working code:  
```python
@ads.response(201, AdSchema)
@ads.arguments(AdSchema)
@jwt_required()
def post(self, data):
    pass
```

Thanks for any idea

**Comment by vimalloc** [comment]
Yes, that is 100% expected. It is outlined in the 4.0.0 breaking changes page: https://flask-jwt-extended.readthedocs.io/en/stable/v4_upgrade_guide/#api-changes.
