### ISSUE TITLE
get_jwt fails if the token is expired.

### ISSUE THREAD

**Issue by zellerman** [vimalloc/flask-jwt-extended#407]
I've implemented the implicit refresh scenario from here
https://flask-jwt-extended.readthedocs.io/en/stable/refreshing_tokens/#implicit-refreshing-with-cookies

And noticed that get_jwt raises a RuntimeError if the jwt was expired, as decoded_jwt at utils.py:22 is None.
Not sure if this is intentional. If yes, what should be called instead?

**Comment by vimalloc** [comment]
Yes, it is intentional, you should never trust an expired token. If a malicious user got their hands of an expired token (could be from minutes, months, or years ago), and you were automatically refreshing it for them, they would have an unlimited pass to access routes as the user who's token was compromised, which would be very bad for security. If someone tries to access your app with an expired token, you should prompt them to re-login using their credentials.

If you find that tokens are expiring faster then you want them to, you can `app.config["JWT_ACCESS_TOKEN_EXPIRES"]` and the `timedelta` in the `after_request` for the code linked.

**Comment by zellerman** [comment]
Makes sense! Thanks. Now I wonder how some webapps let you stay logged in indefinitely. They probably store (at least) the refresh token in localstorage.
