### ISSUE TITLE
how to retrieve csrf_refresh_token using javascript

### ISSUE THREAD

**Issue by copocaneta** [vimalloc/flask-jwt-extended#428]
This is not really an issue, this is just something that I can't figure out.

I am using javascript `fetch()` (with `credentials: 'same-origin'` or `credentials: 'include'`) and when posting to my /login endpoint I can see `csrf_refresh_token` and `refresh_token_cookie` (httpOnly) in DevTools response cookies (I get them at `'Set-Cookie'` response headers).

But I can't use it with javascript `document.cookie`, it is empty. I can't figure out how to retrieve `csrf_refresh_token` using JavaScript.

Can you @vimalloc or somebody else point me in the right direction here?

**Comment by copocaneta** [comment]
I think I might have figured it out, could you please confirm if this is the way?

From what I could gather I won't be able to access `csrf_refresh_token` using JavaScript even though that cookie is not httpOnly (if there is a way to retrieve that using JavaScript please let me know).

So as per this [issue](https://github.com/vimalloc/flask-jwt-extended/issues/111) I set `JWT_CSRF_IN_COOKIES` to `False` and now I am returning the CSRF token to the frontend in my login payload with:

```python
csrf_refresh_token = get_csrf_token(refresh_token)
```

PS: [tokens in cookies](http://flask-jwt-extended.readthedocs.io/en/latest/tokens_in_cookies.html) on docs as per other [issue](https://github.com/vimalloc/flask-jwt-extended/issues/111) is down

**Comment by vimalloc** [comment]
> From what I could gather I won't be able to access csrf_refresh_token using JavaScript even though that cookie is not httpOnly (if there is a way to retrieve that using JavaScript please let me know).

There absolutely is a way. If it isn't working, you are probably running into a web browser security feature that's preventing your javascript from reading the cookies. Make sure your frontend and backend are coming from the same host and port, otherwise the browser probably wont like the cookies you are trying to set. This is commonly done using nginx in production, and weback dev server proxy for local development:  https://webpack.js.org/configuration/dev-server/#devserverproxy.

That said, there is absolutely nothing wrong with setting `JWT_CSRF_IN_COOKIES` to false and using `get_csrf_token` to pass the CSRF token in to the frontend where you can save it in local storate or whatever :+1: 


> PS: tokens in cookies on docs as per other issue is down

That's to be expected, a new major version of Flask-JWT-Extended has been released since that issue was created. The documentation for v4.x.x is here: https://flask-jwt-extended.readthedocs.io/en/stable/token_locations/#cookies

**Comment by copocaneta** [comment]
Thank you so much for the valuable info and also thank you so much for your work on this amazing module.

**Comment by vimalloc** [comment]
Glad to help :+1:
