### ISSUE TITLE
Flask-JWT-Extended With Pluggable Views

### ISSUE THREAD

**Issue by aruncrayons** [vimalloc/flask-jwt-extended#429]
Hai @vimalloc. Can I use Flask-JWT-Extended with **pluggle views** ?

```python
class UserAPI(MethodView):
    decorators = [jwt_required]
```
as per docs we have to follow this way.

I tried:

```python
class UserAPI(MethodView):
    @jwt_required(refresh=True)
    def post(self):
       ...
       return {"msg": "success"}, 200
```

It works. But my question is, is there is any problem for doing so?

**Comment by vimalloc-mavenlink** [comment]
Sorry, this one slipped through the cracks for me. I haven't personally used pluggable views, so I would defer to whatever the flask documentation says around decorators, or just using `verify_jwt_in_request()` directly instead of the decorator approach. This extension shouldn't care one way or the other, as long as `verify_jwt_in_request` gets called (either directly or via the decorator) before your view function is ran, then everything will be fine :+1:

**Comment by Mukhametvaleev** [comment]
@aruncrayons 
> Can I use Flask-JWT-Extended with **pluggle views** ?

**Example 1 – All view methods protection:**
> ```python
> from flask_jwt_extended import verify_jwt_in_request
>
>
> class UserAPI(MethodView):
>     def __init__(self):
>         verify_jwt_in_request()
>
>     def post(self):
>         # ...
>         return {"name": "User"}, 201
> ```

**Example 2 – Specific view method protection:**
> ```python
> from flask_jwt_extended import verify_jwt_in_request
>
>
> class UserAPI(MethodView):
>     def post(self):
>         verify_jwt_in_request()
>         # ...
>         return {"name": "User"}, 201
> ```
