### ISSUE TITLE
Accessing get_jwt_identity() in another decorator.

### ISSUE THREAD

**Issue by genie137** [vimalloc/flask-jwt-extended#44]
Hey, really like the library. Very useful!

I want to use the identity from the JWT in another decorator.
Currently I have (details left out, but you get the gist):
```
@app.Route('/api/,,,'. methods=['GET']
@jwt_required
@service_supported(str(get_jwt_identity()), "SERVICE")
def method1():
    pass

```

In this case the get_jwt_identity() returns {}.
When placed inside method1(), I get the correct result.

Any ideas?

**Comment by vimalloc** [comment]
Basically because of how decorators work, you are creating a new function there which takes get_jwt_identity() as a parameter, and returns a new function based on that. This is calling get_jwt_identity() only once, and returning a new function that has the results of get_jwt_identity as the first argument. Since this was called outside of a requests, it returns an empty value here (Side note, I meant for that get_jwt_identity() called outside of a request to return None, not {}, I'll fix that up later today). The get_jwt_identity() function isn't getting called every request like you would expect, as the end result is method1 gets changed to basically a new function, then that new function gets called at every request.

There are blogs out there which explain this in much better detail then I can, perhaps checkout this: https://realpython.com/blog/python/primer-on-python-decorators/ (just the first one I found when googling). If you have questions about that, you can hit me up and I will try my best to answer them.

As for fixing it up, do you have access to the service_supported code? If you put the get_jwt_identity() in there, it should work how you expect. An example decorator might look something like this:

```python
def service_supported(fn, service_type):
    @wraps(fn)
    def wrapper(*args, **kwargs):
        username =str(get_jwt_identity())
        user = UserObject(username=username)
        if not user.supports_service(service_type):
            raise Exception("User does not support this service")
        return fn(*args, **kwargs)
    return wrapper
```

Hope this helps :)

**Comment by genie137** [comment]
Hey man, 
Thanks for your response!
What you put as an example worked well for me. However when passing an argument to the decorator, it needs to be surrounded by yet another function in order to work.
I`m now in love with decorators, as it fixes a lot of ugly looking if-else statements for me.
I ended up with this and it seems to be working:

```python
def service_support(service):
    def actual_decorator(func):
        @wraps(func)
        def wrapper(*args, **kwargs):
            identity = str(get_jwt_identity())
            if not master_tools.MasterProvider(identity).is_service_supported(service):
                return jsonify({"msg": "Identity does not have rights to view this service."}), 403
            return func(*args, **kwargs)
        return wrapper
    return actual_decorator

```
