### ISSUE TITLE
Refresh token did not working after overrides claim (Not a Bug)

### ISSUE THREAD

**Issue by BRomano** [vimalloc/flask-jwt-extended#457]
I was having a strange error after update library, my refresh token did not work anymore.

Debuging library I found I was overring type key, and library was not finding "refresh" on token.

On _encode_jwt(...)

![image](https://user-images.githubusercontent.com/4623909/139559551-5e44cbd1-1123-49a7-9425-2e971d817a12.png)

I recomend add user information on a specific scope or add a warning for users who do the same as I did.

I changed type to auth_type... did it because google, facebook, and other kind of authentications.
![image](https://user-images.githubusercontent.com/4623909/139559461-fa7fba22-4296-47b2-a162-b64608fd9c57.png)

**Comment by vimalloc** [comment]
This is actually by design. Prior to the 4.x.x release of flask-jwt-extended we did have it setup to put user claims in a nested dictionary, but this ended up causing problems for a lot of users who wanted to be able to dynamically override reserved claims (like iss, exp, aud, etc). This behavior is documented here: https://flask-jwt-extended.readthedocs.io/en/stable/api/#flask_jwt_extended.create_access_token

> additional_claims – Optional. A hash of claims to include in the access token. These claims are merged into the default claims (exp, iat, etc) and claims returned from the additional_claims_loader() callback. On conflict, these claims take prescience.

`type` is probably a bit more confusing, since that isn't technically a reserved claim, but it is a claim that our library is interacting with. I'm absolutely open to any documentation improvements to make this more clear, if you feel like putting together a PR?

**Comment by BRomano** [comment]
Sure will do.

Maybe explain user's and reserved claims are mixed, and highlight all library `reserved` claims.
So user can read and avoid these names.
