### ISSUE TITLE
Check if current_user is authenticated

### ISSUE THREAD

**Issue by carlosvega** [vimalloc/flask-jwt-extended#469]
Hello, I'm just upgrading my code to the 4.x version of flask-jwt-extended

However, I'm struggling to use get_jwt_identity. Before, I could use this method even if the user was not authenticated and it was a way for me to check as well if I should use AnonymousUser or not for some calls. Also it was a way to check during unittests if the user was not authenticated when it returned None, in case of testing a login failure.

Also for forms, whether is new user or editing the current user.

Is there any way to check whether the user is authenticated?

**Comment by vimalloc** [comment]
Yep! So the breaking change is that calling `get_jwt_identity` (and all those related functions) will now throw a `RuntimeError` if they are called without `jwt_required` being called first. This change was due to the fact that a lot of people were running into problems because they either forgot to add `@jwt_required` to their routes, or mixed up the decorator order in their routes causing their code to fire before the JWT was parsed, and leading to bugs around that. There are two ways you could get the old behavior back.

First would be to change your calls to `@jwt_required(optional=True)`. When in an `optional` route, `get_jwt_identity` will still return `None` if no JWT is present in the request. This is probably the more "proper" way, but it may or may not make sense depending on  how everything is setup in your application.

The second would be to build a little wrapper around `get_jwt_identity` and use that as a drop in replacement. This would get you back to exactly how things worked in flask-jwt-extended 3.x.x, and looks like:

```python
from flask_jwt_extended import get_jwt_identity

def get_identity():
    try:
        return get_jwt_identity()
    except RuntimeError:
        return None
```

Hope this helps!

**Comment by carlosvega** [comment]
Thanks for the prompt answer. So this is totally intended behaviour. Good !
I think I will go for the "proper" way as it seems more appropriate. However, I have a question.

How would that work while on a test?
Imagine I would like to test whether a user is authenticated or not during a test. For instance, first I assert that `get_jwt_identity` returns None. Meaning that the user is not logged in. Then I do an action, e.g. API call, which is rejected, since the user is not authenticated. I assert the failure, proceed to login, assert that `get_jwt_identity` is not None and perform the same action and so on and so forth.

How would that work with the new API ?

Before, I was able to do this:

```
user_id = get_jwt_identity()
self.assertEqual(user_id, None)
```

I guess, for now, the only solution would be to get the RuntimeError, right? In this case, wouldn't be better to implement a custom exception for this to avoid potential confusions with other exceptions that might be thrown out? 

Thanks again!

**Comment by vimalloc** [comment]
Yeah, I think that's right. I agree that a different error could be better, I'll add that to a list of small breaking changes I would like to make for the next major version bump, but it will probably be a bit before that happens. 

I don't know if this would be any less janky then catching the `RuntimeError`, but you might be able to do something like this in your tests as another way to handle that:

```python
from flask_jwt_extended import verify_jwt_in_request

def test():
    with app.test_request_context():
        verify_jwt_in_request(optional=True)
        user_id = get_jwt_identity()
        self.assertEqual(user_id, None)
        # login, do the rest of your tests, etc
```
