### ISSUE TITLE
Add more information to the tokens

### ISSUE THREAD

**Issue by faisalabujabal** [vimalloc/flask-jwt-extended#50]
Hello

Big fan of the package!

I've been trying for few hours now to find an efficient way to store more information to the tokens when **JWT_BLACKLIST_ENABLED** is `True`. As far as I can tell the only way to access the token is using _get_stored_token(jti)_, but I don't have access to the _jti_. 

I am trying to avoid using _get_stored_tokens(identity)_ and going over the list. 

Any suggestions?

Thanks

**Comment by faisalabujabal** [comment]
So I did find a way to solve this by doing the following:

```
token = decode_jwt(encoded_token, config.secret_key, config.algorithm, csrf=False)
jti = token['jti']
```
but that involves using the decode function, which I don't think was intended to be used outside the package. Maybe something along the lines of:
```
def get_jti(self, encoded_token, csrf=False):
     return decode_jwt(encoded_token, config.secret_key, config.algorithm, csrf)['jti']
```
would be nice

**Comment by vimalloc** [comment]
Just to verify, you want to get the ```jti``` right after creating a new token? That solution seems like it would be great, only thing I would want to change is csrf flag there. We should be able to just use the csrf value in the config instead of having to pass it in as a kwarg:  ```csrf=config.csrf_protect```.

I can look at adding this later this week, or if you wanted to submit a pull request I could look it over ASAP.

Cheers :)

**Comment by faisalabujabal** [comment]
Great! I'll start working on the PR. What do you think of the `get_stored_token`? Ofcourse anyone that's using the function in their code will have to go and change it.

**Comment by faisalabujabal** [comment]
and what do you think the method should be called? In https://github.com/vimalloc/flask-jwt-extended/issues/22 you suggested that we create `get_jwt_jti`. 

`get_jti` or `get_jwt_jti`?

**Comment by vimalloc** [comment]
As long as you put the ```encoded_token``` kwarg after ```jti``` (and make that a kwarg as well, like you have it in your example), it shouldn't cause any breaking changes for current users. It can currently be called it via ```get_stored_token('abc123')``` or ```get_stored_token(jti=`abc123`)```, and both of those will still work with your proposed changes. This seems fine to me.

As per the name, I think ```get_jti``` is fine. In this case, we are passing in the encoded token directly ex: ```get_jti(encoded_token)``` instead of grabbing it from the flask context stack, so I think that fits the overall naming convention better.

**Comment by faisalabujabal** [comment]
Done! https://github.com/vimalloc/flask-jwt-extended/pull/51

I was also curious why wasn't `simplekv` included in requirements.txt?

**Comment by vimalloc** [comment]
Thanks! 👍 

And good catch with the reqiurements.txt, it absolutely should be in there. Looks like it was accidently removed in adff7b2affe6647d1f9d00864b2ba21b9605b8f6. I'll get it re-added
