### ISSUE TITLE
Version Logs? 

### ISSUE THREAD

**Issue by rlam3** [vimalloc/flask-jwt-extended#57]
@vimalloc Should we have a log of changes to clarify if newer releases might break previous versions?

**Comment by vimalloc** [comment]
It wouldn't hurt I suppose, we could even have a full changelog if we wanted, although [this page](https://github.com/vimalloc/flask-jwt-extended/releases) kind of acts like that already. 

We are using Semantic versioning, so if there is a breaking change it should be accompanied by a major number bumb (ex, going from 2.x.x to 3.x.x), otherwise newer versions of the library should work on older code bases without any issues. There is one caveat to that though, if someone is dipping into the internals of the code (for example, importing stuff that is not exported by ```__init__.py```, those could change out from under them. But ideally people wouldn't be using the internals that way, and if there was a feature they needed to access we could move it into the ```__init__.py``` export list to add that guarantee to it.

Just curious, is this a hypothetical question, or did a recent change cause a breaking issue for you?

**Comment by rlam3** [comment]
@vimalloc Thanks! 

This is more of a hypothetical question because I want to be able to do auto updates with this package and I trust that it won't break in next versions. Or it has some sort of backward compatibility in the long run. But this may be too much of an assumption...

;p

**Comment by vimalloc** [comment]
I try very hard not to make breaking changes (only adding new things or fixing bugs, not breaking existing things). If I do need to make a major breaking change it will be accompanied by a major version number increase (bring us to the 3.x.x branch), and information on migrating to the new code in the README.

That said, I am planning to make a breaking change soon with how I token blacklisting is handled. The related issues for that is #25 and #58, and after this change will give developers a lot more control on the underlying data store. If you aren't using the blacklisting feature, you will not have to do anything, but if you are using that feature, I'll have some drop in replacement code you can use to migrate to the 3.x branch. Besides that, unless something major comes up I don't anticipate any breaking changes in the foreseeable future.

Hope this helps!

Cheers :)

**Comment by rlam3** [comment]
@vimalloc Thank you so much for pointing out this change. Even though I don't have blacklisting integrated, really do appreciate the effort and time you are putting into this project. 

Cheers!
