### ISSUE TITLE
Docs - porting from flask-jwt

### ISSUE THREAD

**Issue by mixmastamyk** [vimalloc/flask-jwt-extended#61]
Thanks for the hard work.

Looking though the docs it appears this extension is similar to flask-jwt but not identical.  Would be nice to have a section in the docs on how to port to the newer library and any associated concerns there might be.  So far I've noticed:

- JWT --> JWTManager(app)
- Need to create an auth view method 
- Config: 

  - JWT_AUTH_HEADER_PREFIX  --> JWT_HEADER_TYPE
  - JWT_EXPIRATION_DELTA -->  JWT_ACCESS_TOKEN_EXPIRES

- No leeway

Is that a good start?

**Comment by vimalloc** [comment]
At a glance it looks like a good start, but I'm sure there is more that would need to go in there. I haven't used flask-jwt in quite a while, so this probably isn't comprehensive, but some other things I can think of right off hand are:

* Doesn't require a function to load users from a token. We have the option to do that, but I'm sure the way we set that up is different than in flask-jwt
* You have to create your own auth endpoint that generates tokens (with create_access_token() and create_refresh_token() methods), instead of letting flask-jwt handle this for you. The reason for this is to give the programmer more power and not lock them into one way of doing things.
* Support for all the optional features (blacklisting, refresh tokens, fresh tokens, cookies, csrf, etc).
* I'm guessing there are probably more option names that are different between the two libraries, but don't know right off hand what they would be.
* Different way to add custom data into the JWT claims and change errors that are raised when invalid tokens are encountered.

At it's core, this is a different library then flask-jwt (it isn't a fork of flask-jwt, it was built from the ground up). If you wanted to put together some documentation for migrating from flask-jwt, I would totally welcome a pull request. If you are just curious for yourself, I think looking at these are a good start, but poking through the documentation would be your best bet (and I'm available on IRC to answer any questions you might have).

Cheers! :)
