### ISSUE TITLE
unset_jwt_cookies always returns refresh_token cookie

### ISSUE THREAD

**Issue by adonis28850** [vimalloc/flask-jwt-extended#71]
This method always sets the `refresh_token` related cookies, even if the app is not using them:

https://github.com/vimalloc/flask-jwt-extended/blob/master/flask_jwt_extended/utils.py#L188
https://github.com/vimalloc/flask-jwt-extended/blob/master/flask_jwt_extended/utils.py#L204

Maybe add a check so it only returns them if the app needs them, or additionally create 2 methods to unset each of them (similar to what you do to set them initially)?

**Comment by vimalloc** [comment]
Hrm. There isn't any way to determine if refresh tokens are being used by just looking at the flask-jwt-extended options, so that wouldn't work. I don't want to add a breaking change to the current `unset_jwt_cookies` either, as I don't think the hassle that would cause is worth it. I don't see how unsetting that cookie, even if you aren't using it, could be a security concert, so the only downside is sending some extra bytes when doing a logout, and that should be very minimal.

Was there a specific reason you need this functionality, or is it to keep from sending unnecessary bytes on logging out? If there is a good reason, we could add two additional methods on top of the `unset_jwt_cookies` method (something like `unset_access_cookies` and `unset_refresh_cookies`), so that you could use those. That wouldn't be hard to add, and then we could redefine `usnset_jwt_cookies` to use those behind the scenes.

**Comment by adonis28850** [comment]
Yeah nothing serious to be honest, I just saw it and thought it may be better to split it, but if as you say the hassle is too much then never mind, not a big deal!

If you go for it though, I think having unset_access_cookies and unset_refresh_cookies is possible the best option.
