### ISSUE TITLE
Better separate handling of access tokens and refresh tokens

### ISSUE THREAD

**Issue by psafont** [vimalloc/flask-jwt-extended#72]
Right now access tokens and refresh tokens are JWT. The library requires the claim 'type' to tell them apart, this makes the library not friendly to external token providers.

From what I've seen, there is no need for refresh tokens to be JWT, they could be base64-encoded random strings, as seen on auth0's blog: https://auth0.com/blog/refresh-tokens-what-are-they-and-when-to-use-them/ This solution would mean that the code securing endpoint with jwt would not need to worry about finding some custom claims in the tokens, meaning it could also accept external token providers.

Of course, this would most probably mean breaking backwards compatibility, (especially access tokens and blacklists)

I wanted to open the ticket to gather thoughts and opinions on this. It's something I'd like to get integrated into the library as it benefits me and I think it could benefit the library as well, it's something I could implement. (at least after returning from vacations)

**Comment by vimalloc** [comment]
> From what I've seen, there is no need for refresh tokens to be JWT, they could be base64-encoded random strings, as seen on auth0's blog: https://auth0.com/blog/refresh-tokens-what-are-they-and-when-to-use-them/

As I understand it, this would require the user to have state on their server to go this route, as you now need to be able to look which user the refresh base64 encoded string is for. Unfortunately, that is something I don't want to require for using token refreshing in this application.

If there is another way to make this extension work for your use case, I will consider it. One thing to keep in mind is this library really is opinionated in how it works, and that is kinda by design. It grants a lot of power to developers to do complex things involving JWTs easy in the context of this library, but it isn't a general solution for all JWT scenarios (as you have noticed), and it wont always work with other schemes.

I would be more then happy to go over other ideas you might have to get this working for you, but if your end goal is to basically have a flask application that can consume tokens from other providers, it might be simpler for you to use PyJWT directly. It is a really simple api for handling JWTs (without all the extra stuff I have included in this library), and writing a `@jwt_required` decorator that uses it shouldn't be too difficult at all.

Anyways, hope this give you some food for though. Let me know if you have any questions /comments about this. (and enjoy your vacations!) :)

**Comment by vimalloc** [comment]
In case you are interested in this, or someone else stumbles upon this, let me introduce Flask-JWT-Simple (https://github.com/vimalloc/flask-jwt-simple). It is a toned down version of this extension with all the opinionated stuff needed for the extra features ripped out. This new extension allow you full control over claims when creating JWTs, and places no restrictions on what claims need to be in consumed JWTs.

If there are features missing from the simple variant of this extension that you would like to see, I would be more then happy to port them over. The two that I could see being helpful right off hand is JWT blacklisting and JWT claim verification.

Cheers.

**Comment by psafont** [comment]
Sorry I didn't reply sooner/

I actually followed your recommendation and did my own thing, it looks a lot like a more stripped-down version your flask-jwt-simple, since I don't have to be as generic (at least for the time being).

Thanks for your efforts!
