### ISSUE TITLE
Microservice with flask-jet-extended?

### ISSUE THREAD

**Issue by rlam3** [vimalloc/flask-jwt-extended#84]
@vimalloc Have you tried using flask-jwt-extended with microservice architecture? If so, would love your input on how to use jwt to communicate with other microservices. Thanks!

**Comment by vimalloc** [comment]
I haven't tried that before (in fact, I haven't really designed any microservices before), so take everything I say here with a large grain of salt. 

It sounds like there would be two 'obvious' ways to use JWTs with microservices right off hand. The first way would be to have a central proxy endpoint that did the JWT verification, then forwarded the request to a different microservice that no longer had the `@jwt_required` protection applied to the endpoints. The advantages of this would seem to be that you get your authentication and verification happening in only one place, so it would be easier to make changes going forward. The disadvantages might be that you need to take extra care that the other microservices cannot be called anywhere besides that proxy server, and figuring out a good way to pass context from the JWT (username, roles, custom claims, etc). to the microservice endpoints that need them.

The other way I can think off right off hand would be to use public/private (asymmetric) crypto. You could have your server that handles authentication have both the public and private key, and use the private key be used to sign new JWTs that you pass out. Then in all the rest of your microservices, you only need to store the public key which can be used to decrypt and verify the JWTs. Going this route you would need to keep the `@jwt_required` decorator around on all your endpoints in the microservices, but if a service gets compromised your whole system doesn't get compromised (unless it is the authentication server of course). I imagine this solution would be easier to engineer then the proxy solution above, but has the drawbacks where you may need to update all your microservices if you change the public/private key or what data is stored in the JWTs. Without doing tests, I couldn't guess which one of these solutions would be faster.

If I was designing a system like this, I would personally start with the second approach just because I think it would be easier to get up and running with, and then consider switching over to the first approach as needed.

Hope this helps! :)
