### ISSUE TITLE
How to specify audience?

### ISSUE THREAD

**Issue by psyvision** [vimalloc/flask-jwt-extended#85]
Hello,

We are consuming a JWT token from an AWS Cognito Identity Pool that has an "aud" claim specified for the audience.  The base JWT decode function is throwing an `InvalidAudienceException` because there is an audience specified in the token but not in the configuration/call to `jwt.decode()`.

Is there a way to specify this in configuration?

**Comment by vimalloc** [comment]
Currently this can be done in flask-jwt-simple, but not in flask-jwt-extended (http://flask-jwt-simple.readthedocs.io/en/latest/change_jwt_claims.html), although I am not against adding a way to do it in this extension.

Flask-JWT-Simple is the sister extension of this one, with all the opinionated stuff needed to get the extra features working (cookie csrf protection, fresh vs non-fresh, refresh tokens, etc) stripped out. For these reasons, it might be a better choice when interfacing with other JWT consumers/providers. That said, there is no reason why I couldn't add the ability to change 'aud' claim to this extension. If that would be helpful, I can try to get a new version out with that in the next day or so. It would probably look something like this:

```python
access_token = create_access_token(identity='foo', aud='bar')
```

Cheers

**Comment by psyvision** [comment]
Thank you for getting back to me.

We are actually using the simple package but I queried here given this one
is more feature rich.

We aren't creating the token with the library here, just wanting to
validate it on a flask API. I'm not sure your solution is viable in that
it's the call to jwt.decode() that requires an additional audience
parameter to be specified, see the Audience Claim section of these docs -
http://pyjwt.readthedocs.io/en/latest/usage.html

**Comment by psyvision** [comment]
Just seen your second reply, wow we're doing good here!!

An additional config option would be fantastic! Thank you.

**Comment by vimalloc** [comment]
I'm going to close this now that it is resolved on flask-jwt-simple. If you run into any problems, don't hesitate to open a new issue. Cheers.

**Comment by JefferyLiangNZ** [comment]
I knew this ticket has been closed, and I understand that you suggested on switching to Flask-JWT-Simple. However, there is a few features that I would like to stick with Flask-JWT-Extend. (functions such as blacklist feature)

We use Cognito Idp as the main source of IDP, and based on to most vendor doc, we wish to use "Access token" instead of "Identity token" to access any backend services, because "access token"  is normally an opaque token and thus expose little identity info.

What I get our application wortking with Extend, is almost the clone of your wonderful examples  "examples/oidc.py" 

I made little tweak so that JWT_DECODE_AUDIENCE become None, and my jwt_public_key use the second set of algorithm param sets. This is necessary so that the underlying call of jwt.decode will ignore the aud check. which doesn't exists as the part of "access_token"

```    
      FLASK_CONFIG.update(
        JWT_PUBLIC_KEY = jwt.algorithms.RSAAlgorithm.from_jwk(json.dumps(oidc_jwks_uri['keys'][1])),
        JWT_ALGORITHM = oidc_jwks_uri['keys'][1]['alg'], # RS256
        JWT_DECODE_AUDIENCE  = None,
        JWT_IDENTITY_CLAIM = OIDC_USERNAME_CLAIM
    )
```


First of all it is a Cognito IDP, so upon the implicit authoritzationl, I have access_token and id_token.

Then I all the API requests will be accompanied with "Authorization" filled by "access bearer token". This JWT contains claims including "jti" and "exp", making it suitable for blacklist check.
This JWT contains client_id, making it useful (not directly applicable) for checking AUD.  I currently use one line code to check the equality. ` jwt['client_id'] == "OIDC_CLIENT_ID" `
