### ISSUE TITLE
Claims verification and storing info in sub

### ISSUE THREAD

**Issue by fgblomqvist** [vimalloc/flask-jwt-extended#90]
I used the simple version of this module for a few weeks of development but just switched to the extended since I needed the dynamic expiration time (some of my tokens will expire sooner than others). Furthermore, I also needed a way to verify that certain data existed in the JWT. So far, I have stored all the user info in the identity (sub) as a dictionary that includes the user id, plus everything else that would be important to know about the user (permissions, a couple of association ids, name, etc.). I needed a way to verify that at least some of this data exists in the token before considering it valid, so I thought I could use the `claims_verification_loader` to do that. Obviously, I was wrong and what that loader does is verify whatever is stored inside the `user_claims` claim.

First of all, I might be wrong, but I thought it was ok to store extended user info in the `sub` claim? (haven't found any rules or other opinions about it) Assuming that is fine, shouldn't there be callback to be able to verify that data?

Second of all, if it is not okay to store extended info (e.g. info other than a user id) in the `sub` claim, I think it would be nice to be able to name the `user_claims` claim yourself (through the config). Personally, the name `user_claims` sounds a bit redundant. I would prefer to have it named `user` or `user_info`, or even `sub_info` (this one makes semantically the most sense). Since it boils down to opinion, I think putting it in the config would be the best.

But all in all I think this module is really handy and simplifies a lot of things, good job so far +1

**Comment by vimalloc** [comment]
Per the first point, the general convention is to store addition claims in the `user_claims` key via the `user_claims_loader` decorator (http://flask-jwt-extended.readthedocs.io/en/latest/add_custom_data_claims.html). That said, this is just a convention, it is not enforced. You can absolutely store whatever you want in the identity/sub claim. 

You can still use the `claims_verification_loader` for data stored in the subs claim, you will just need to get it yourself (with `get_jwt_identity()` or `get_raw_jwt()`) instead of having it passed in via the function args. The reason the function takes the `user_claims` data as an argument is just to make it easier to use and clearer on what it does.

Per the second case, being able to change the name of the `user_claims` seems totally reasonable to me. If you wanted to submit a pull request with that change I would be happy to help get it merged. I can also look at adding it myself when I have some free time on my hands.

Hopefully this helps. Let me know if you have any follow up questions.

**Comment by fgblomqvist** [comment]
Thanks for such a quick response. Didn't realize I could do that, but that's smart. I'll try to get a PR done later today as well, can't hurt with more configurability (considering this is the extended version after all)!

**Comment by vimalloc** [comment]
Thanks!! 👍

**Comment by fgblomqvist** [comment]
Actually, just tried getting the identity using `get_jwt_identity()` and it just got None. Checked the source and the JWT is not on the stack yet (because the validation happens before it gets put on the stack) and therefore it is not possible to get it. In other words: for this to work the token needs to be added to the stack before the validation, or something like that.

**Comment by vimalloc** [comment]
oh, my bad. I thought I called the validation stuff after it was on the stack, but obviously I was mistaken.

Having access to the identity of the token (regardless of what is stored in that claim) seems like could be helpful to have for the verification method. I'm guessing the best way to do that without breaking the api would be to move the validation of claims after it is added to the stack, but I want to think on that for a bit.

**Comment by fgblomqvist** [comment]
No worries. It is possible to work around this by utilizing the user_loader callback (since it has access to the identity) and write a clearer error message:
```
@jwtm.user_loader_callback_loader
def user_loader_callback_loader(identity):
    if 'MY_FIELD' not in identity:
        return None
    return {}

@jwtm.user_loader_error_loader
def user_loader_error_loader(identity):
    return jsonify({'error': "missing fields in jwt"}), 422
```
Obviously, user loading can be done at the same time as well. I'll use this for now, until you've come up with a better solution (no rush). I'll still try to get the PR done for the other stuff today though.

**Comment by vimalloc** [comment]
added in 3.3.3
